import assert from 'node:assert/strict';
import {normalizeQuestionHistory,reserveQuestionHistory,gradeQuestionHistory,QUESTION_WINDOW_MS} from '../src/question-policy.js';
const beforeMidnight=Date.parse('2026-09-23T15:59:00Z');
const afterMidnight=Date.parse('2026-09-23T16:01:00Z');
let history=normalizeQuestionHistory(null,beforeMidnight);
history=reserveQuestionHistory(history,[1,2,3],beforeMidnight);
history=normalizeQuestionHistory(history,afterMidnight);
assert.throws(()=>reserveQuestionHistory(history,[1],afterMidnight),/Question conflict/,'normal questions cannot repeat across midnight');
history=gradeQuestionHistory(history,[{index:2,answer:'wrong'}],i=>String(i));
assert.equal(history.pending[2],true,'incorrect question must remain pending');
history=reserveQuestionHistory(history,[2],afterMidnight);
history=gradeQuestionHistory(history,[{index:2,answer:'still wrong'}],i=>String(i));
assert.equal(history.pending[2],true,'a repeated wrong answer must stay eligible');
history=reserveQuestionHistory(history,[2],afterMidnight+1);
history=gradeQuestionHistory(history,[{index:2,answer:'2'}],i=>String(i));
assert.equal(history.pending[2],undefined,'correct answer clears wrong-answer exception');
assert.throws(()=>reserveQuestionHistory(history,[2],afterMidnight+2),/Question conflict/);
history=normalizeQuestionHistory(history,beforeMidnight+QUESTION_WINDOW_MS+1000);
assert.doesNotThrow(()=>reserveQuestionHistory(history,[1],beforeMidnight+QUESTION_WINDOW_MS+1000),'normal questions unlock after 24h');
assert.throws(()=>reserveQuestionHistory(history,[10,10,1200],afterMidnight),/Invalid questions/);
console.log('P1 24-hour rollover, wrong-until-correct and index validation: PASS');
