import assert from 'node:assert/strict';
import {emptyRpg,cleanRpg,rollLoot,rollMythicLoot,addLoot,equipItem,synthesisInfo,synthesizeItem,equipmentResonance,collectionEntries,collectionProgress,crystallizeItem,petSkillEffects,recordTowerFloor,mythicEquipmentEffects} from '../src/rpg.js';
import {makeFighter,resolveCardAction} from '../src/cards.js';
const seq=vals=>{let i=0;return ()=>vals[Math.min(i++,vals.length-1)]};
const loot=(q=.1,type=.1,sub=.1)=>rollLoot(3,50,seq([0,q,type,sub]));
assert.equal(collectionEntries().length,30);
let r=emptyRpg();const a=loot(),b=loot(),c=loot();r=addLoot(addLoot(addLoot(r,a),b),c);assert.equal(collectionProgress(r).owned,1);assert.equal(synthesisInfo(r,a.id).can,true);r=synthesizeItem(r,a.id);assert.equal(r.inventory.filter(x=>x.subtype==='ruby'&&x.quality==='rare').length,1);assert.ok(r.collection.includes('gem:ruby:common'));assert.ok(r.collection.includes('gem:ruby:rare'));
let keep=emptyRpg();const t=loot(.1,.1,.9);keep=addLoot(keep,t);const key=`${t.type}:${t.subtype}:${t.quality}`;keep=crystallizeItem(keep,t.id);assert.ok(keep.collection.includes(key));
let res=emptyRpg();const r1=loot(),r2=loot(),wr=loot(.1,.9,.1);for(const x of [r1,r2,wr])res=addLoot(res,x);res=equipItem(res,r1.id);res=equipItem(res,r2.id);res=equipItem(res,wr.id);assert.equal(equipmentResonance(res).firstCardAmp,.12);
const base=makeFighter({maxHp:500,hp:500,atk:100,def:50,crit:0,role:'mage',pet:null,rpg:emptyRpg()}),boosted=makeFighter({maxHp:500,hp:500,atk:100,def:50,crit:0,role:'mage',pet:null,rpg:res}),target1=makeFighter({maxHp:1000,hp:1000,def:50,crit:0}),target2=makeFighter({maxHp:1000,hp:1000,def:50,crit:0}),card={id:'stat-atk',kind:'stat',stat:'atk',pct:20,color:'red',name:'test'};resolveCardAction(base,target1,card,3,{cards:[card],slotIndex:0});resolveCardAction(boosted,target2,card,3,{cards:[card],slotIndex:0});assert.ok(boosted.atk>base.atk);
let aw=emptyRpg();aw.petEnhance.fox=4;aw=cleanRpg(aw);assert.ok(petSkillEffects('fox',aw).firstCardAmp>=.15);
let tower=recordTowerFloor(emptyRpg(),7);tower=recordTowerFloor(tower,4);assert.equal(tower.towerBest,7);
const noMyth=rollMythicLoot({boss:false,towerFloor:7,level:50},seq([0,.1]));assert.equal(noMyth,null);
const bossMyth=rollMythicLoot({boss:true,level:50},seq([.01,.01]));assert.equal(bossMyth.quality,'mythic');assert.equal(synthesisInfo(addLoot(emptyRpg(),bossMyth),bossMyth.id).can,false);
let myth=addLoot(emptyRpg(),bossMyth);myth=equipItem(myth,bossMyth.id);assert.ok(mythicEquipmentEffects(myth).redAmp>0);
const highTower=rollMythicLoot({towerFloor:10,level:50},seq([.05,.9]));assert.equal(highTower.quality,'mythic');
console.log('RPG systems OK');
