import assert from 'node:assert/strict';
import fs from 'node:fs';
const nodes=new Map(),storage=new Map();
const app={_html:'',set innerHTML(html){this._html=String(html);nodes.clear()},get innerHTML(){return this._html},querySelector:()=>null,querySelectorAll:()=>[]};
function element(selector,dataset={}){
  const key=selector+JSON.stringify(dataset);
  if(!nodes.has(key))nodes.set(key,{dataset,hidden:false,textContent:'',value:'',handlers:{},addEventListener(name,fn){this.handlers[name]=fn},click(){const fn=this.handlers.click;assert.equal(typeof fn,'function','missing event handler on '+selector);return fn()},focus(){},select(){}});
  return nodes.get(key);
}
function matches(selector){
  const m=selector.match(/^\[([^\]=]+)(?:="([^"]*)")?\]$/);
  if(!m)return null;
  const marker=m[2]===undefined?m[1]:m[1]+'="'+m[2]+'"';
  return app.innerHTML.includes(marker)?m:null;
}
globalThis.document={
  getElementById:()=>({}),addEventListener(){},
  querySelector(selector){if(selector==='#app')return app;const match=matches(selector);if(!match)return null;if(match[2]!==undefined&&match[1].startsWith('data-')){const attr=match[1],key=attr.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return this.querySelectorAll('['+attr+']').find(node=>node.dataset[key]===match[2])||null}return element(selector)},
  querySelectorAll(selector){
    const m=selector.match(/^\[data-([a-z-]+)\]$/);
    if(!m)return [];
    const attr=m[1],key=attr.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),pattern=new RegExp('data-'+attr+'="([^"]+)"','g');
    return [...app.innerHTML.matchAll(pattern)].map((item,i)=>element(selector+':'+i,{[key]:item[1]}));
  }
};
globalThis.Audio=class{pause(){}play(){return Promise.resolve()}getAttribute(){return ''}};
globalThis.location={search:'',pathname:'/',hash:''};
globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
storage.set('word-rpg-card-v3',JSON.stringify({authMode:'guest',wordBook:{entries:{0:{correct:1,wrong:0,first:'correct',lastAt:1}}}}));
let clipboard='',spoken=[];
globalThis.window={speechSynthesis:{cancel(){},speak:u=>spoken.push({text:u.text,lang:u.lang})}};
globalThis.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:async text=>{clipboard=text}}}});
await import('../src/game-core.js');
assert.match(app.innerHTML,/data-action="guest-login"/);
document.querySelector('[data-action="guest-login"]').click();
const home=app.innerHTML;
const identity=home.match(/<div class="growth-level">([\s\S]*?)<\/div><div class="player-season-tier">/);
assert.ok(identity,'player info must live in right-side growth panel directly above season');
assert.match(identity[1],/^<b class="growth-level-value">LV1<\/b><span class="growth-title">[^<]+<\/span><span class="growth-player-name">訪客<\/span>$/,'three distinct identity lines must be level, title, player name');
assert.ok(home.indexOf('class="role-growth-art"')<home.indexOf('class="role-growth-panel"'),'character art should remain in the left column');
const homeStyles=fs.readFileSync(new URL('../src/game-v2.css',import.meta.url),'utf8');
assert.match(homeStyles,/\.role-feature \.role-growth-art img\s*\{[^}]*height:415px/,'desktop character art must be enlarged');
assert.match(homeStyles,/@media\(max-width:700px\)[\s\S]*?\.role-feature \.role-growth-art img\s*\{[^}]*height:345px/,'mobile character art must be enlarged');
for(const id of ['quests','achievements','community'])assert.match(home,new RegExp('data-action="'+id+'"'),id+' button missing');
assert.doesNotMatch(home,/data-action="daily"/,'combined daily/achievement button must disappear');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const typography=fs.readFileSync(new URL('../src/typography.css',import.meta.url),'utf8');
assert.ok(html.includes('./src/typography.css'),'all game screens must load the light typography sheet');
assert.ok(html.indexOf('./src/typography.css')>html.indexOf('./src/progression-v2.css'),'light typography must load after all existing styles');
assert.match(typography,/body \*::after\s*\{\s*font-weight:300!important;/,'all UI text, including pseudo elements, must be light weight');
const assets=fs.readFileSync(new URL('../src/assets.js',import.meta.url),'utf8');
for(const name of ['Quest.png','Achievement.png','Community.png'])assert.ok(assets.includes('/images/'+name),'uploaded button image not wired: '+name);
for(const [id,order] of [['pet-tree',13],['equipment',14],['quests',16],['achievements',17],['community',18]])assert.ok(assets.includes(`[data-action="${id}"]{order:${order}`),'wrong visual button row/order: '+id);
assert.match(assets,/\.collection-entry\{order:15/,'collection must be the last button of row 2');
document.querySelector('[data-action="pet-tree"]').click();
assert.match(app.innerHTML,/寵物專屬技能樹/);
assert.match(app.innerHTML,/迅影突襲/);
assert.match(app.innerHTML,/赤焰獵手/);
assert.match(app.innerHTML,/月影守護/);
assert.equal((app.innerHTML.match(/class="pet-branch pet-branch-/g)||[]).length,3,'selected pet must show three distinct tree lanes');
assert.equal((app.innerHTML.match(/data-pet-skill="fox\|fox-/g)||[]).length,9,'selected fox must show nine actual purchasable skills');
assert.doesNotMatch(app.innerHTML,/data-pet-skill="owl\|owl-/,'unselected owl tree must be hidden');
document.querySelector('[data-pet="owl"]').click();
assert.match(app.innerHTML,/星夜智識/);
assert.match(app.innerHTML,/聖羽療癒/);
assert.equal((app.innerHTML.match(/data-pet-skill="owl\|owl-/g)||[]).length,9);
assert.doesNotMatch(app.innerHTML,/data-pet-skill="fox\|fox-/,'changing pet replaces lower tree');
document.querySelector('[data-pet="dragon"]').click();
assert.match(app.innerHTML,/元素術式/);
assert.match(app.innerHTML,/真龍滅擊/);
assert.match(app.innerHTML,/龍鱗護體/);
assert.equal((app.innerHTML.match(/data-pet-skill="dragon\|dragon-/g)||[]).length,9);
document.querySelector('[data-action="setup-back"]').click();
assert.match(app.innerHTML,/data-action="pet-tree"/,'return from pet menu must preserve original home navigation');
document.querySelector('[data-action="quests"]').click();
assert.match(app.innerHTML,/每日任務/);
assert.match(app.innerHTML,/data-daily-chest/);
assert.doesNotMatch(app.innerHTML,/英文學習與冒險成就/,'achievement claims belong only to achievements');
document.querySelector('[data-action="setup-back"]').click();
document.querySelector('[data-action="achievements"]').click();
for(const heading of ['英文學習與冒險成就','單字精熟成就','裝備收集成就','稱號收藏'])assert.ok(app.innerHTML.includes(heading),heading+' missing');
assert.match(app.innerHTML,/data-equip-title=/,'earned title must be equippable from achievement screen');
assert.doesNotMatch(app.innerHTML,/data-daily-chest/,'daily chest belongs only to quests');
document.querySelector('[data-action="setup-back"]').click();
document.querySelector('[data-action="collection"]').click();
assert.doesNotMatch(app.innerHTML,/collection-rewards/,'collection rewards must move to achievements');
document.querySelector('[data-collection-tab="words"]').click();
assert.doesNotMatch(app.innerHTML,/單字精熟系統|首次作答才收錄|累積答對 1 次|答錯 0 次/,'requested verbose word-book text must be removed');
assert.match(app.innerHTML,/data-word-speak="0"/,'collected words must be playable');
document.querySelector('[data-word-speak="0"]').click();
assert.equal(spoken.length,1,'clicking word card must speak exactly once');
assert.equal(spoken[0].lang,'en-US');
assert.doesNotMatch(app.innerHTML,/data-word-title=/,'title selection must move out of vocabulary collection');
document.querySelector('[data-action="setup-back"]').click();
document.querySelector('[data-action="community"]').click();
assert.match(app.innerHTML,/data-community-share/);assert.match(app.innerHTML,/data-social-app|id="social-app"/);
assert.match(app.innerHTML,/data-community-pk/);
await document.querySelector('[data-community-copy]').click();
assert.match(clipboard,/Word RPG/);
assert.match(clipboard,/https:\/\/word-rpg\.redfisharthur\.workers\.dev\//);
console.log('P1 UI hubs: third icon row, separate quests/achievements, centralized titles, and working community invite: PASS');
