import assert from 'node:assert/strict';
import {WORD_BOOK_SIZE,WORD_MASTERED_AT,WORD_TITLES,emptyWordBook,cleanWordBook,recordWordAnswer,wordStatus,wordBookProgress,unlockedWordTitles,equipWordTitle} from '../src/word-book.js';

let book=emptyWordBook();
assert.deepEqual(wordBookProgress(book),{collected:0,mastered:0,focus:0,learning:0});
assert.equal(WORD_MASTERED_AT,4);
book=recordWordAnswer(book,17,true,1);
assert.equal(wordStatus(book.entries['17']),'學習中','first right answer must collect as learning');
book=recordWordAnswer(book,24,false,2);
assert.equal(wordStatus(book.entries['24']),'重點詞彙','first wrong answer must collect as focus');
book=recordWordAnswer(book,24,true,3);
assert.equal(wordStatus(book.entries['24']),'重點詞彙','wrong-word focus remains until mastered');
book=recordWordAnswer(book,17,false,4);
assert.equal(wordStatus(book.entries['17']),'重點詞彙','a later mistake should flag the word');
for(let i=0;i<3;i++)book=recordWordAnswer(book,24,true,5+i);
assert.equal(book.entries['24'].correct,4);
assert.equal(wordStatus(book.entries['24']),'精熟');
assert.equal(wordBookProgress(book).mastered,1);
assert.equal(wordBookProgress(book).collected,2,'repeat answers never duplicate words');
book=recordWordAnswer(book,24,false,9);
assert.equal(wordStatus(book.entries['24']),'精熟','mastered status depends on cumulative correct answers');
book=recordWordAnswer(book,WORD_BOOK_SIZE,true);
book=recordWordAnswer(book,-1,true);
assert.equal(wordBookProgress(book).collected,2,'invalid indices never appear in the book');

let raw={entries:{}};
for(let i=0;i<100;i++)raw.entries[i]={correct:4,wrong:0,first:'correct',lastAt:1};
let progress=wordBookProgress(raw);
assert.equal(progress.mastered,100);
assert.equal(unlockedWordTitles(raw).length,0,'exactly 100 mastered words is not over 100');
raw=recordWordAnswer(raw,100,true);
for(let i=0;i<3;i++)raw=recordWordAnswer(raw,100,true);
assert.equal(unlockedWordTitles(raw)[0]?.required,101);
assert.equal(raw.activeTitle,WORD_TITLES[0].name,'new title is automatically equipped');
raw=equipWordTitle(raw,WORD_TITLES[2].name);
assert.equal(raw.activeTitle,WORD_TITLES[0].name,'locked title cannot be equipped');
for(let i=101;i<301;i++)raw.entries[i]={correct:4,wrong:0,first:'correct',lastAt:2};
assert.equal(unlockedWordTitles(raw).length,2,'301 mastered unlocks second title');
raw=recordWordAnswer(raw,301,true);
assert.equal(raw.activeTitle,WORD_TITLES[0].name,'additional unmastered words do not change the active title');
for(let i=301;i<801;i++)raw.entries[i]={correct:4,wrong:0,first:'correct',lastAt:3};
assert.equal(unlockedWordTitles(raw).length,3,'801 mastered unlocks third title');
raw=equipWordTitle(raw,WORD_TITLES[2].name);
assert.equal(raw.activeTitle,WORD_TITLES[2].name);
const saved=JSON.parse(JSON.stringify(raw));
assert.equal(cleanWordBook(saved).activeTitle,WORD_TITLES[2].name);
assert.equal(wordBookProgress(cleanWordBook(saved)).mastered,801);
const invalid=cleanWordBook({entries:{'-1':{correct:999,wrong:0},'1200':{correct:999,wrong:0},'0':{correct:-4,wrong:2}},activeTitle:'任意假稱號'});
assert.equal(wordBookProgress(invalid).collected,1);
assert.equal(invalid.activeTitle,'');
console.log('Word collection: first attempts, 4 correct, unique 101/301/801 title thresholds, saves: PASS');
