import {DurableObject} from 'cloudflare:workers';
import {dealHand,makeFighter,resolveCards,resolveBasic,afterAction,cloneFighter} from '../src/cards.js';

const WORD_COUNT=30;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const qset=()=>Array.from({length:3},()=>Math.floor(Math.random()*WORD_COUNT));
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/match'){const id=env.MATCHMAKER.idFromName('global-matchmaker');return env.MATCHMAKER.get(id).fetch(request)}return env.ASSETS.fetch(request)}};

export class Matchmaker extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
  async fetch(request){if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({id:crypto.randomUUID(),state:'new',profile:null,opponentId:null,matchId:null,fighter:null,hand:null,used:[],round:1,ready:null});server.send(JSON.stringify({type:'connected'}));return new Response(null,{status:101,webSocket:client})}
  webSocketMessage(ws,message){let data;try{data=JSON.parse(typeof message==='string'?message:new TextDecoder().decode(message))}catch{return}if(data.type==='join')this.join(ws,data.profile||{});if(data.type==='ready')this.ready(ws,data)}
  profile(p){return {name:String(p.name||'PLAYER').slice(0,16),role:['warrior','mage','archer'].includes(p.role)?p.role:'warrior',pet:['fox','owl','dragon'].includes(p.pet)?p.pet:'fox'}}
  send(ws,data){try{ws.send(JSON.stringify(data))}catch{}}
  find(id){return this.ctx.getWebSockets().find(x=>x.deserializeAttachment()?.id===id)}
  view(att){return {...cloneFighter(att.fighter),profile:att.profile}}
  join(ws,p){let att=ws.deserializeAttachment()||{};att={...att,state:'waiting',profile:this.profile(p),fighter:makeFighter(),hand:dealHand(),used:[],round:1,ready:null};ws.serializeAttachment(att);const other=this.ctx.getWebSockets().find(x=>x!==ws&&x.deserializeAttachment()?.state==='waiting');if(!other){this.send(ws,{type:'queued'});return}let oa=other.deserializeAttachment();const matchId=crypto.randomUUID();att={...att,state:'matched',opponentId:oa.id,matchId};oa={...oa,state:'matched',opponentId:att.id,matchId};ws.serializeAttachment(att);other.serializeAttachment(oa);const questions=qset();this.send(ws,{type:'matched',self:this.view(att),opponent:this.view(oa),hand:att.hand,questions});this.send(other,{type:'matched',self:this.view(oa),opponent:this.view(att),hand:oa.hand,questions})}
  cleanReady(data,att){const correct=clamp(Math.round(Number(data.correct)||0),0,3),elapsedMs=clamp(Math.round(Number(data.elapsedMs)||60000),200,60000);const available=att.hand.map((_,i)=>i).filter(i=>!att.used.includes(i));let selected=[];if(att.round<3){selected=[...new Set((Array.isArray(data.selected)?data.selected:[]).map(Number).filter(i=>available.includes(i)))].slice(0,2);if(selected.length!==2)return null}return {correct,elapsedMs,selected}}
  ready(ws,data){let a=ws.deserializeAttachment();if(!a||a.state!=='matched'||a.ready)return;const ready=this.cleanReady(data,a);if(!ready){this.send(ws,{type:'error',message:'出牌資料錯誤'});return}a.ready=ready;ws.serializeAttachment(a);const other=this.find(a.opponentId);if(!other){this.send(ws,{type:'opponent-left'});return}let b=other.deserializeAttachment();if(!b?.ready){this.send(ws,{type:'waiting-opponent'});return}this.resolvePair(ws,a,other,b)}
  resolvePair(ws,a,other,b){const A=a.fighter,B=b.fighter,ra=a.ready,rb=b.ready,round=a.round,logsA=[],logsB=[];const cardsA=round<3?ra.selected.map(i=>a.hand[i]):[],cardsB=round<3?rb.selected.map(i=>b.hand[i]):[];const first=ra.elapsedMs<=rb.elapsedMs?'a':'b';const act=(who)=>{if(A.hp<=0||B.hp<=0)return;if(who==='a'){logsA.push(...(round===3?resolveBasic(A,B,ra.correct):resolveCards(A,B,cardsA,ra.correct)));afterAction(A,B,logsA)}else{logsB.push(...(round===3?resolveBasic(B,A,rb.correct):resolveCards(B,A,cardsB,rb.correct)));afterAction(B,A,logsB)}};act(first);act(first==='a'?'b':'a');if(round<3){a.used.push(...ra.selected);b.used.push(...rb.selected)}a.fighter=A;b.fighter=B;const finished=round>=3||A.hp<=0||B.hp<=0;let winner=null;if(finished){const ar=A.hp/A.maxHp,br=B.hp/B.maxHp;winner=Math.abs(ar-br)<.0001?'draw':ar>br?'a':'b';a.state='finished';b.state='finished'}else{a.round++;b.round++;a.ready=null;b.ready=null}ws.serializeAttachment(a);other.serializeAttachment(b);const nextQuestions=finished?null:qset();const commonA={type:'battle-result',round,self:this.view(a),opponent:this.view(b),correct:ra.correct,logs:logsA,orderText:first==='a'?`你先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`,finished,winner:winner==='a'?'self':winner==='b'?'opponent':winner,nextQuestions};const commonB={type:'battle-result',round,self:this.view(b),opponent:this.view(a),correct:rb.correct,logs:logsB,orderText:first==='b'?`你先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`,finished,winner:winner==='b'?'self':winner==='a'?'opponent':winner,nextQuestions};this.send(ws,commonA);this.send(other,commonB)}
  webSocketClose(ws){const a=ws.deserializeAttachment();if(!a?.opponentId)return;const other=this.find(a.opponentId);if(other){this.send(other,{type:'opponent-left'});const b=other.deserializeAttachment();if(b){b.state='finished';other.serializeAttachment(b)}}}
  webSocketError(ws){this.webSocketClose(ws)}
}
