import {DurableObject} from 'cloudflare:workers';
import {dealHand,makeFighter,resolveCardAction,resolveBasic,resolveAutoBasic,afterAction,cloneFighter,bondMultiplier,supportBoost,isOffensive,applyPetRoundEnd,progressionStats} from '../src/cards.js';
import {cleanRpg,maxedPkRpg} from '../src/rpg.js';
import {makeQuestion} from '../src/words.js';
import {cleanDaily} from '../src/daily.js';
import {QUESTION_WINDOW_MS,normalizeQuestionHistory,reserveQuestionHistory,gradeQuestionHistory} from '../src/question-policy.js';

const WORD_COUNT=1200;
const SESSION_COOKIE='word_rpg_session';
const GUEST_COOKIE='word_rpg_guest';
const OAUTH_STATE_COOKIE='word_rpg_oauth_state';
const OAUTH_VERIFIER_COOKIE='word_rpg_oauth_verifier';
const OAUTH_NONCE_COOKIE='word_rpg_oauth_nonce';
const SESSION_SECONDS=60*60*24*30;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fighterSnapshot=f=>{const out=cloneFighter(f);delete out.rpg;return out};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const parseCookies=request=>Object.fromEntries((request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const at=x.indexOf('=');return at<0?[x,'']:[x.slice(0,at),decodeURIComponent(x.slice(at+1))]}));
const cookie=(name,value,maxAge)=>`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const clearCookie=name=>cookie(name,'',0);
const bytesToBase64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const textToBase64Url=text=>bytesToBase64Url(new TextEncoder().encode(text));
const base64UrlToText=value=>{const s=value.replace(/-/g,'+').replace(/_/g,'/'),p=s+'='.repeat((4-s.length%4)%4);return new TextDecoder().decode(Uint8Array.from(atob(p),c=>c.charCodeAt(0)))};
const randomToken=(length=32)=>{const bytes=new Uint8Array(length);crypto.getRandomValues(bytes);return bytesToBase64Url(bytes)};
async function sha256Base64Url(value){return bytesToBase64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))))}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return bytesToBase64Url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))))}
async function makeSession(profile,env){const secret=env.SESSION_SECRET||env.LINE_CHANNEL_SECRET;if(!secret)throw new Error('Missing session secret');const now=Math.floor(Date.now()/1000),payload={sub:profile.userId,name:profile.name||'LINE 玩家',picture:profile.picture||'',iat:now,exp:now+SESSION_SECONDS},encoded=textToBase64Url(JSON.stringify(payload)),sig=await hmac(secret,encoded);return `${encoded}.${sig}`}
async function readSession(request,env){const token=parseCookies(request)[SESSION_COOKIE];if(!token)return null;const [encoded,sig]=String(token).split('.');if(!encoded||!sig)return null;const secret=env.SESSION_SECRET||env.LINE_CHANNEL_SECRET;if(!secret)return null;const expected=await hmac(secret,encoded);if(sig!==expected)return null;try{const payload=JSON.parse(base64UrlToText(encoded));if(!payload.sub||!payload.exp||payload.exp<Math.floor(Date.now()/1000))return null;return payload}catch{return null}}
const dailyDate=()=>new Date(Date.now()+8*60*60*1000).toISOString().slice(0,10);
const seasonId=()=>dailyDate().slice(0,7);
const seasonDefaults=()=>({season:seasonId(),points:0,wins:0,losses:0,draws:0});
function cleanSeason(raw={}){const current=seasonId();if(raw?.season!==current)return seasonDefaults();return {season:current,points:Math.max(0,Math.round(Number(raw.points)||0)),wins:Math.max(0,Math.round(Number(raw.wins)||0)),losses:Math.max(0,Math.round(Number(raw.losses)||0)),draws:Math.max(0,Math.round(Number(raw.draws)||0))}}
async function questionIdentityKeys(request,env){const session=await readSession(request,env);if(session?.sub)return [`line:${session.sub}`];const guest=parseCookies(request)[GUEST_COOKIE];return /^[0-9a-f-]{36}$/i.test(guest||'')?[`guest:${guest}`]:[];}
function issueGuestIdentity(request){const old=parseCookies(request)[GUEST_COOKIE];if(/^[0-9a-f-]{36}$/i.test(old||''))return {key:`guest:${old}`,setCookie:null};const id=crypto.randomUUID();return {key:`guest:${id}`,setCookie:cookie(GUEST_COOKIE,id,SESSION_SECONDS)};}
async function identityApi(request,env){if(request.method!=='GET')return json({error:'Method not allowed'},405);if((await readSession(request,env))?.sub)return json({ok:true});const g=issueGuestIdentity(request);return json({ok:true},200,g.setCookie?{'Set-Cookie':g.setCookie}:{});}
const questionStub=(env,key)=>env.USER_STORE.get(env.USER_STORE.idFromName(`questions:${key}`));
const userStub=(env,userId)=>env.USER_STORE.get(env.USER_STORE.idFromName(userId));
async function usedQuestions(env,key){const res=await questionStub(env,key).fetch('https://user/questions');if(!res.ok)throw new Error('題庫紀錄讀取失敗');const data=await res.json();return {seen:data.seen||{},pending:new Set(Array.isArray(data.pending)?data.pending:[])};}
async function markQuestions(env,key,indices){return questionStub(env,key).fetch('https://user/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({indices})});}
async function recordQuestionAnswers(env,keys,indices,answers){if(!keys?.length)return;const results=indices.map((index,i)=>({index,answer:answers[i]==null?'':String(answers[i])}));for(const key of [...new Set(keys)]){const res=await questionStub(env,key).fetch('https://user/questions/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({results})});if(!res.ok)throw new Error('錯題紀錄更新失敗');}}
async function reserveDailyQuestions(env,keys,count){const unique=[...new Set(keys)],need=clamp(Math.round(Number(count)||1),1,20);if(!unique.length)throw new Error('題庫身分未建立，請重新進入遊戲');for(let attempt=0;attempt<8;attempt++){const states=await Promise.all(unique.map(key=>usedQuestions(env,key))),available=[];for(let i=0;i<WORD_COUNT;i++)if(states.every(q=>!q.seen[i]||q.pending.has(i)))available.push(i);if(available.length<need)throw new Error('過去 24 小時內的不重複題目已完成，請稍後再試');const pending=available.filter(i=>states.some(q=>q.pending.has(i))).sort((x,y)=>Math.min(...states.map(q=>Number(q.seen[x])||0))-Math.min(...states.map(q=>Number(q.seen[y])||0)));const fresh=available.filter(i=>!states.some(q=>q.pending.has(i)));for(let i=fresh.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[fresh[i],fresh[j]]=[fresh[j],fresh[i]]}const chosen=[...pending,...fresh].slice(0,need);let conflict=false;for(const key of unique){const res=await markQuestions(env,key,chosen);if(res.status===409){conflict=true;break}if(!res.ok)throw new Error('題庫紀錄失敗')}if(!conflict)return chosen}throw new Error('題庫忙碌，請再試一次');}
async function questionsApi(request,env){if(request.method!=='GET')return json({error:'Method not allowed'},405);const count=clamp(Math.round(Number(new URL(request.url).searchParams.get('count'))||10),1,20),keys=await questionIdentityKeys(request,env),guest=keys.length?null:issueGuestIdentity(request);if(guest)keys.push(guest.key);try{return json({indices:await reserveDailyQuestions(env,keys,count),count},200,guest?.setCookie?{'Set-Cookie':guest.setCookie}:{})}catch(err){return json({error:err?.message||'題庫暫時無法使用'},429,guest?.setCookie?{'Set-Cookie':guest.setCookie}:{})}}
async function questionResultApi(request,env){if(request.method!=='POST')return json({error:'Method not allowed'},405);const keys=await questionIdentityKeys(request,env);if(!keys.length)return json({error:'題庫身分未建立'},401);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const results=Array.isArray(body.results)?body.results:[];if(!results.length||results.length>20)return json({error:'Invalid results'},400);try{const indices=results.map(x=>x.index),answers=results.map(x=>x.answer);await recordQuestionAnswers(env,keys,indices,answers);return json({ok:true})}catch(err){return json({error:err?.message||'題庫紀錄更新失敗'},409)}}
async function userSeason(env,userId){if(!userId)return null;const res=await userStub(env,userId).fetch(`https://user/season?season=${encodeURIComponent(seasonId())}`);if(!res.ok)return seasonDefaults();return cleanSeason(await res.json())}
async function updateUserSeason(env,userId,result){if(!userId)return null;const res=await userStub(env,userId).fetch('https://user/season',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({season:seasonId(),result})});if(!res.ok)return null;return cleanSeason(await res.json())}
function callbackUrl(url,env){return env.LINE_CALLBACK_URL||`${url.origin}/auth/line/callback`}
function progressDefaults(){return {role:'warrior',pet:'fox',level:1,xp:0,rpg:cleanRpg(),daily:cleanDaily()}}
function cleanProgress(input={}){const level=clamp(Math.round(Number(input.level)||1),1,80);return {role:['warrior','mage','archer'].includes(input.role)?input.role:'warrior',pet:['fox','owl','dragon'].includes(input.pet)?input.pet:'fox',level,xp:level>=80?0:Math.max(0,Math.round(Number(input.xp)||0)),rpg:cleanRpg(input.rpg),daily:cleanDaily(input.daily)}}
async function userProgress(env,userId){const res=await userStub(env,userId).fetch('https://user/progress');if(!res.ok)return progressDefaults();return cleanProgress(await res.json())}
async function saveUserProgress(env,userId,progress){return userStub(env,userId).fetch('https://user/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cleanProgress(progress))})}
async function beginLineLogin(request,env){if(!env.LINE_CHANNEL_ID||!env.LINE_CHANNEL_SECRET)return new Response('LINE Login 尚未設定：請先設定 LINE_CHANNEL_ID 與 LINE_CHANNEL_SECRET。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});const url=new URL(request.url),state=randomToken(),verifier=randomToken(48),nonce=randomToken(),challenge=await sha256Base64Url(verifier),redirect=callbackUrl(url,env),auth=new URL('https://access.line.me/oauth2/v2.1/authorize');auth.search=new URLSearchParams({response_type:'code',client_id:env.LINE_CHANNEL_ID,redirect_uri:redirect,state,scope:'openid profile',nonce,code_challenge:challenge,code_challenge_method:'S256'}).toString();const headers=new Headers({Location:auth.toString(),'Cache-Control':'no-store'});headers.append('Set-Cookie',cookie(OAUTH_STATE_COOKIE,state,600));headers.append('Set-Cookie',cookie(OAUTH_VERIFIER_COOKIE,verifier,600));headers.append('Set-Cookie',cookie(OAUTH_NONCE_COOKIE,nonce,600));return new Response(null,{status:302,headers})}
async function finishLineLogin(request,env){const url=new URL(request.url),cookies=parseCookies(request),state=url.searchParams.get('state'),code=url.searchParams.get('code');const fail=()=>Response.redirect(`${url.origin}/?line=error`,302);if(!code||!state||state!==cookies[OAUTH_STATE_COOKIE]||!cookies[OAUTH_VERIFIER_COOKIE])return fail();try{const redirect=callbackUrl(url,env),tokenRes=await fetch('https://api.line.me/oauth2/v2.1/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirect,client_id:env.LINE_CHANNEL_ID,client_secret:env.LINE_CHANNEL_SECRET,code_verifier:cookies[OAUTH_VERIFIER_COOKIE]})});if(!tokenRes.ok)return fail();const token=await tokenRes.json();if(!token.id_token)return fail();const verifyRes=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:token.id_token,client_id:env.LINE_CHANNEL_ID})});if(!verifyRes.ok)return fail();const verified=await verifyRes.json();if(!verified.sub||verified.nonce!==cookies[OAUTH_NONCE_COOKIE])return fail();let name=verified.name||'',picture=verified.picture||'';if((!name||!picture)&&token.access_token){const profileRes=await fetch('https://api.line.me/v2/profile',{headers:{Authorization:`Bearer ${token.access_token}`}});if(profileRes.ok){const profile=await profileRes.json();name=name||profile.displayName||'';picture=picture||profile.pictureUrl||''}}const session=await makeSession({userId:verified.sub,name,picture},env),headers=new Headers({Location:`${url.origin}/?line=1`,'Cache-Control':'no-store'});headers.append('Set-Cookie',cookie(SESSION_COOKIE,session,SESSION_SECONDS));headers.append('Set-Cookie',clearCookie(OAUTH_STATE_COOKIE));headers.append('Set-Cookie',clearCookie(OAUTH_VERIFIER_COOKIE));headers.append('Set-Cookie',clearCookie(OAUTH_NONCE_COOKIE));return new Response(null,{status:302,headers})}catch{return fail()}}
async function sessionApi(request,env){const session=await readSession(request,env);if(!session)return json({authenticated:false});const [progress,season]=await Promise.all([userProgress(env,session.sub),userSeason(env,session.sub)]);return json({authenticated:true,profile:{userId:session.sub,name:session.name,picture:session.picture||''},progress,season})}
async function progressApi(request,env){if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=new URL(request.url),origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Forbidden'},403);const session=await readSession(request,env);if(!session)return json({error:'Unauthorized'},401);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const progress=cleanProgress(body),res=await saveUserProgress(env,session.sub,progress);if(!res.ok)return json({error:'Save failed'},500);return json({ok:true,progress})}
async function seasonApi(request,env){if(request.method!=='GET')return json({error:'Method not allowed'},405);const session=await readSession(request,env);if(!session)return json({error:'Unauthorized'},401);return json({season:await userSeason(env,session.sub)})}
function logout(request){const url=new URL(request.url),headers=new Headers({Location:url.origin+'/'});headers.append('Set-Cookie',clearCookie(SESSION_COOKIE));return new Response(null,{status:302,headers})}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/match'){const id=env.MATCHMAKER.idFromName('global-matchmaker');return env.MATCHMAKER.get(id).fetch(request)}if(url.pathname==='/auth/line')return beginLineLogin(request,env);if(url.pathname==='/auth/line/callback')return finishLineLogin(request,env);if(url.pathname==='/api/session')return sessionApi(request,env);if(url.pathname==='/api/progress')return progressApi(request,env);if(url.pathname==='/api/questions')return questionsApi(request,env);if(url.pathname==='/api/question-identity')return identityApi(request,env);if(url.pathname==='/api/questions/result')return questionResultApi(request,env);if(url.pathname==='/api/season')return seasonApi(request,env);if(url.pathname==='/auth/logout')return logout(request);return env.ASSETS.fetch(request)}};

export class UserStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
  async fetch(request){const url=new URL(request.url);
    if(url.pathname==='/questions'||url.pathname==='/questions/result'){
      const now=Date.now(),old=await this.ctx.storage.get('questionHistoryV2');
      const legacy=old?null:await this.ctx.storage.get('dailyQuestions');
      const history=normalizeQuestionHistory(old,now,legacy,WORD_COUNT);
      if(url.pathname==='/questions'&&request.method==='GET')return json({seen:history.seen,pending:Object.keys(history.pending).map(Number)});
      if(request.method!=='POST')return json({error:'Method not allowed'},405);
      let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}
      let next;
      try{
        if(url.pathname==='/questions')next=reserveQuestionHistory(history,Array.isArray(body.indices)?body.indices:[],now,WORD_COUNT);
        else next=gradeQuestionHistory(history,body.results,i=>makeQuestion(i).answer,WORD_COUNT);
      }catch(err){return json({error:err?.message||'Invalid questions'},err?.message==='Question conflict'||err?.message==='Question was not issued'?409:400)}
      await this.ctx.storage.put('questionHistoryV2',next);
      return json({ok:true});
    }
    if(url.pathname==='/season'){const current=url.searchParams.get('season')||seasonId();let record=cleanSeason(await this.ctx.storage.get('season')||seasonDefaults());if(record.season!==current)record=seasonDefaults();if(request.method==='GET')return json(record);if(request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}record=cleanSeason(await this.ctx.storage.get('season')||seasonDefaults());const result=String(body.result||'');if(!['win','loss','draw'].includes(result))return json({error:'Invalid result'},400);if(result==='win'){record.wins++;record.points+=18}else if(result==='loss'){record.losses++;record.points=Math.max(0,record.points-8)}else{record.draws++;record.points+=4}await this.ctx.storage.put('season',record);return json(record)}return json({error:'Method not allowed'},405)}
    if(request.method==='GET'){const progress=await this.ctx.storage.get('progress')||progressDefaults();return json(cleanProgress(progress))}if(request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const progress=cleanProgress(body);await this.ctx.storage.put('progress',progress);return json(progress)}return json({error:'Method not allowed'},405)}
}

export class Matchmaker extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
  async fetch(request){if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const session=await readSession(request,this.env),questionKeys=await questionIdentityKeys(request,this.env);if(!questionKeys.length)questionKeys.push(`temporary:${crypto.randomUUID()}`);const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({id:crypto.randomUUID(),userId:session?.sub||null,state:'new',profile:null,opponentId:null,matchId:null,fighter:null,hand:null,used:[],round:1,ready:null,selection:null,quizStartedAt:0,questionKeys,questionBatch:[],queuedAt:0,botId:null});server.send(JSON.stringify({type:'connected'}));return new Response(null,{status:101,webSocket:client})}
  async webSocketMessage(ws,message){let data;try{data=JSON.parse(typeof message==='string'?message:new TextDecoder().decode(message))}catch{return}if(data.type==='join')await this.join(ws,data.profile||{});if(data.type==='quiz-start')this.beginQuiz(ws,data);if(data.type==='ready')await this.ready(ws,data)}
  profile(p){return {name:String(p.name||'PLAYER').slice(0,16),role:['warrior','mage','archer'].includes(p.role)?p.role:'warrior',pet:['fox','owl','dragon'].includes(p.pet)?p.pet:'fox',level:80,rpg:maxedPkRpg()}}
  send(ws,data){try{ws.send(JSON.stringify(data))}catch{}}
  find(id){return this.ctx.getWebSockets().find(x=>x.deserializeAttachment()?.id===id)}
  view(att){const fighter=fighterSnapshot(att.fighter);const p=att.profile||{};return {...fighter,profile:{name:p.name,role:p.role,pet:p.pet,level:p.level}}}

  async scheduleQueueAlarm(){const deadlines=this.ctx.getWebSockets().map(ws=>ws.deserializeAttachment()).filter(a=>a?.state==='waiting'&&a.queuedAt).map(a=>a.queuedAt+60000);if(deadlines.length)await this.ctx.storage.setAlarm(Math.max(Date.now()+100,Math.min(...deadlines)));}
  async alarm(){const now=Date.now();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(a?.state==='waiting'&&a.queuedAt&&now-a.queuedAt>=60000)await this.matchBot(ws)}await this.scheduleQueueAlarm();}
  async matchBot(ws){let a=ws.deserializeAttachment();if(!a||a.state!=='waiting')return;
    a.state='matching';ws.serializeAttachment(a);let batch;try{batch=await reserveDailyQuestions(this.env,a.questionKeys||[],10)}catch(err){a.state='finished';ws.serializeAttachment(a);this.send(ws,{type:'error',message:err?.message||'題庫暫時無法使用'});return}
    const roles=['warrior','mage','archer'],pets=['fox','owl','dragon'];
    const role=roles[Math.floor(Math.random()*roles.length)],pet=pets[Math.floor(Math.random()*pets.length)],profile=this.profile({name:'AI 挑戰者',role,pet}),stats=progressionStats(role,pet,profile.level,profile.rpg).total;
    const b={id:`bot:${crypto.randomUUID()}`,state:'matched',profile,fighter:makeFighter({...stats,role,pet,rpg:profile.rpg}),hand:dealHand(9,role,profile.level),used:[],round:1,ready:null,selection:null,quizStartedAt:0,questionBatch:[],bot:true};
    a={...a,state:'matched',opponentId:b.id,botId:b.id,matchId:crypto.randomUUID(),questionBatch:[...batch]};ws.serializeAttachment(a);
    await this.ctx.storage.put(`bot:${a.id}`,b);this.send(ws,{type:'matched',self:this.view(a),opponent:this.view(b),hand:a.hand,bot:true});
  }
  selectBotCards(bot,enemy){const available=bot.hand.map((card,i)=>i).filter(i=>!bot.used.includes(i)),chosen=[],hp=bot.fighter.hp/Math.max(1,bot.fighter.maxHp),enemyHp=enemy.hp/Math.max(1,enemy.maxHp);
    for(let slot=0;slot<3;slot++){const ranked=available.filter(i=>!chosen.includes(i)).map(i=>{const c=bot.hand[i],attack=isOffensive(c);let score=attack?70:30;
      if(c.exclusive)score+=37;if(c.id==='boost')score+=slot===0?70:-15;
      if(c.kind==='stat'){score+=(c.stat==='atk'||c.stat==='crit')?(slot===0?45:6):c.stat==='def'?(hp<.6?45:10):(hp<.65?85:3);}
      if(c.id==='restore'||c.id==='regen')score+=hp<.45?105:hp<.75?56:-30;
      if(c.id==='diamond'||c.id==='aegis')score+=hp<.5?65:12;
      if(c.id==='break'||c.id==='poison'||c.id==='preempt')score+=slot===0?38:14;
      if(c.id==='combo'||c.id==='sun')score+=25;if(c.id==='sacrifice')score+=hp<.4?-150:enemyHp<.4?75:5;
      if(slot===2&&attack)score+=30;if(chosen.some(j=>bot.hand[j]?.id==='boost')&&attack)score+=42;
      return {i,score:score+Math.random()*4}}).sort((a,b)=>b.score-a.score);if(ranked.length)chosen.push(ranked[0].i)}
    return chosen;
  }
  async join(ws,p){let att=ws.deserializeAttachment()||{};const profile=this.profile(p),stats=progressionStats(profile.role,profile.pet,profile.level,profile.rpg).total;att={...att,state:'waiting',queuedAt:Date.now(),botId:null,profile,fighter:makeFighter({...stats,role:profile.role,pet:profile.pet,rpg:profile.rpg}),hand:dealHand(9,profile.role,profile.level),used:[],round:1,ready:null,selection:null,quizStartedAt:0,questionBatch:[]};ws.serializeAttachment(att);const other=this.ctx.getWebSockets().find(x=>x!==ws&&x.deserializeAttachment()?.state==='waiting'&&(!att.userId||x.deserializeAttachment()?.userId!==att.userId));if(!other){this.send(ws,{type:'queued'});await this.scheduleQueueAlarm();return}let oa=other.deserializeAttachment(),batch;att.state='matching';oa.state='matching';ws.serializeAttachment(att);other.serializeAttachment(oa);try{batch=await reserveDailyQuestions(this.env,[...(att.questionKeys||[]),...(oa.questionKeys||[])],10)}catch(err){att.state='finished';oa.state='finished';ws.serializeAttachment(att);other.serializeAttachment(oa);this.send(ws,{type:'error',message:err?.message||'今日題庫已完成'});this.send(other,{type:'error',message:err?.message||'今日題庫已完成'});return}const matchId=crypto.randomUUID();att={...att,state:'matched',opponentId:oa.id,matchId,questionBatch:[...batch]};oa={...oa,state:'matched',opponentId:att.id,matchId,questionBatch:[...batch]};ws.serializeAttachment(att);other.serializeAttachment(oa);this.send(ws,{type:'matched',self:this.view(att),opponent:this.view(oa),hand:att.hand});this.send(other,{type:'matched',self:this.view(oa),opponent:this.view(att),hand:oa.hand})}
  beginQuiz(ws,data){let a=ws.deserializeAttachment();if(!a||a.state!=='matched'||a.ready||a.selection)return;const available=a.hand.map((_,i)=>i).filter(i=>!a.used.includes(i)),selected=[...new Set((Array.isArray(data.selected)?data.selected:[]).map(Number).filter(i=>available.includes(i)))].slice(0,3);if(selected.length!==3){this.send(ws,{type:'error',message:'出牌資料錯誤'});return}const start=(a.round-1)*5,questions=(a.questionBatch||[]).slice(start,start+5);if(questions.length!==5){this.send(ws,{type:'error',message:'題目同步失敗'});return}a.selection=selected;a.quizStartedAt=Date.now();ws.serializeAttachment(a);this.send(ws,{type:'quiz-started',round:a.round,questions:questions.map(i=>{const {word,options}=makeQuestion(i);return {word,options}})})}
  cleanReady(data,att){if(att.round>2||!Array.isArray(att.selection)||att.selection.length!==3||!att.quizStartedAt)return null;const answers=Array.isArray(data.answers)?data.answers.map(v=>v==null?'':String(v).slice(0,80)):[];if(answers.length!==5)return null;const start=(att.round-1)*5,indices=(att.questionBatch||[]).slice(start,start+5);if(indices.length!==5)return null;const rawMs=Date.now()-att.quizStartedAt;if(rawMs<4300||rawMs>65000)return null;let correct=0;for(let i=0;i<5;i++)if(answers[i]===String(makeQuestion(indices[i]).answer))correct++;const elapsedMs=clamp(Math.round(rawMs-4500),200,50000);return {correct,elapsedMs,selected:[...att.selection]}}
  async ready(ws,data){let a=ws.deserializeAttachment();if(!a||a.state!=='matched'||a.ready)return;const ready=this.cleanReady(data,a);if(!ready){this.send(ws,{type:'error',message:'答題資料驗證失敗'});return}
    const indices=(a.questionBatch||[]).slice((a.round-1)*5,a.round*5);
    try{await recordQuestionAnswers(this.env,a.questionKeys||[],indices,data.answers)}catch(err){this.send(ws,{type:'error',message:err?.message||'錯題紀錄更新失敗'});return}
    a.ready=ready;ws.serializeAttachment(a);
    if(a.botId){let bot=await this.ctx.storage.get(`bot:${a.id}`);if(!bot||bot.id!==a.botId){this.send(ws,{type:'error',message:'AI 對戰資料已失效'});return}
      const chosen=this.selectBotCards(bot,a.fighter);if(chosen.length!==3){this.send(ws,{type:'error',message:'AI 卡牌資料不足'});return}
      bot.selection=[...chosen];bot.ready={correct:bot.round===1?5:4,elapsedMs:7800,selected:[...chosen]};
      const virtual={deserializeAttachment:()=>bot,serializeAttachment:value=>{bot=value}};
      await this.resolvePair(ws,a,virtual,bot);await this.ctx.storage.put(`bot:${a.id}`,bot);return;
    }
    const other=this.find(a.opponentId);if(!other){this.send(ws,{type:'opponent-left'});return}let b=other.deserializeAttachment();if(!b?.ready){this.send(ws,{type:'waiting-opponent'});return}await this.resolvePair(ws,a,other,b)}
  async resolvePair(ws,a,other,b){
    const A=a.fighter,B=b.fighter,ra=a.ready,rb=b.ready,round=a.round,cardsA=round<=2?ra.selected.map(i=>a.hand[i]):[],cardsB=round<=2?rb.selected.map(i=>b.hand[i]):[],first=ra.elapsedMs<=rb.elapsedMs?'a':'b',sequence=[];
    if(first==='a')sequence.push('a','b','a','b','a','b');else sequence.push('b','a','b','a','b','a');
    const counts={a:0,b:0},stateA={pendingBoost:1,offensiveCount:0},stateB={pendingBoost:1,offensiveCount:0},stepsA=[],stepsB=[],allLogsA=[],allLogsB=[];
    const doCard=(actor,target,card,correct,pair,slot,state,speedWin)=>{const bond=bondMultiplier(pair,card);let boost=1;if(state.pendingBoost>1&&card?.id!=='boost'){boost=state.pendingBoost;state.pendingBoost=1}const offensiveIndex=state.offensiveCount,logs=resolveCardAction(actor,target,card,correct,{bond,boost,offensiveIndex,cards:pair,slotIndex:slot,speedWin});if(card?.id==='boost')state.pendingBoost=supportBoost(card,actor);if(isOffensive(card))state.offensiveCount++;afterAction(actor,target,logs);return logs};
    for(let i=0;i<sequence.length;i++){const who=sequence[i];if(A.hp<=0||B.hp<=0)break;const slot=counts[who]++;let logs=[],card=null;if(who==='a'){card=cardsA[slot];logs=doCard(A,B,card,ra.correct,cardsA,slot,stateA,first==='a')}else{card=cardsB[slot];logs=doCard(B,A,card,rb.correct,cardsB,slot,stateB,first==='b')}if(who==='a')allLogsA.push(...logs);else allLogsB.push(...logs);stepsA.push({who:who==='a'?'self':'opponent',slot,cycle:round,finalRound:false,card,self:fighterSnapshot(A),opponent:fighterSnapshot(B),logs:[...logs]});stepsB.push({who:who==='b'?'self':'opponent',slot,cycle:round,finalRound:false,card,self:fighterSnapshot(B),opponent:fighterSnapshot(A),logs:[...logs]})}
    if(round<=2){const petLogsA=[],petLogsB=[];applyPetRoundEnd(A,cardsA,petLogsA);applyPetRoundEnd(B,cardsB,petLogsB);allLogsA.push(...petLogsA);allLogsB.push(...petLogsB);if(stepsA.length){stepsA[stepsA.length-1].logs.push(...petLogsA);stepsA[stepsA.length-1].self=fighterSnapshot(A);stepsA[stepsA.length-1].opponent=fighterSnapshot(B)}if(stepsB.length){stepsB[stepsB.length-1].logs.push(...petLogsB);stepsB[stepsB.length-1].self=fighterSnapshot(B);stepsB[stepsB.length-1].opponent=fighterSnapshot(A)}a.used.push(...ra.selected);b.used.push(...rb.selected)}
    if(round===2&&A.hp>0&&B.hp>0){for(let autoRound=3;autoRound<=10&&A.hp>0&&B.hp>0;autoRound++){const starter=(autoRound-3)%2===0?first:(first==='a'?'b':'a'),order=[starter,starter==='a'?'b':'a'];for(const who of order){if(A.hp<=0||B.hp<=0)break;let logs=[];if(who==='a'){logs=resolveAutoBasic(A,B);afterAction(A,B,logs);allLogsA.push(...logs)}else{logs=resolveAutoBasic(B,A);afterAction(B,A,logs);allLogsB.push(...logs)}stepsA.push({who:who==='a'?'self':'opponent',slot:0,cycle:autoRound,autoDuel:true,finalRound:autoRound===10,card:null,self:fighterSnapshot(A),opponent:fighterSnapshot(B),logs:[...logs]});stepsB.push({who:who==='b'?'self':'opponent',slot:0,cycle:autoRound,autoDuel:true,finalRound:autoRound===10,card:null,self:fighterSnapshot(B),opponent:fighterSnapshot(A),logs:[...logs]})}}}
    a.fighter=A;b.fighter=B;const finished=round>=2||A.hp<=0||B.hp<=0;let winner=null;
    if(finished){if(A.hp<=0&&B.hp<=0)winner='draw';else if(B.hp<=0)winner='a';else if(A.hp<=0)winner='b';else winner=A.hp===B.hp?'draw':A.hp>B.hp?'a':'b';a.state='finished';b.state='finished'}else{a.round++;b.round++;a.ready=null;b.ready=null;a.selection=null;b.selection=null;a.quizStartedAt=0;b.quizStartedAt=0}
    let seasonA=null,seasonB=null;if(finished){const resultA=winner==='a'?'win':winner==='b'?'loss':'draw',resultB=winner==='b'?'win':winner==='a'?'loss':'draw';[seasonA,seasonB]=await Promise.all([updateUserSeason(this.env,a.userId,resultA),updateUserSeason(this.env,b.userId,resultB)])}
    ws.serializeAttachment(a);other.serializeAttachment(b);const orderText=first==='a'?`你先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`;
    this.send(ws,{type:'battle-result',round,self:this.view(a),opponent:this.view(b),correct:ra.correct,logs:allLogsA,steps:stepsA,opponentCards:cardsB,orderText,finished,winner:winner==='a'?'self':winner==='b'?'opponent':winner,season:seasonA});
    this.send(other,{type:'battle-result',round,self:this.view(b),opponent:this.view(a),correct:rb.correct,logs:allLogsB,steps:stepsB,opponentCards:cardsA,orderText:first==='b'?`你先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`,finished,winner:winner==='b'?'self':winner==='a'?'opponent':winner,season:seasonB})
  }
  webSocketClose(ws){const a=ws.deserializeAttachment();if(!a?.opponentId)return;const other=this.find(a.opponentId);if(other){this.send(other,{type:'opponent-left'});const b=other.deserializeAttachment();if(b){b.state='finished';other.serializeAttachment(b)}}}
  webSocketError(ws){this.webSocketClose(ws)}
}
