import {DurableObject} from 'cloudflare:workers';
import {dealHand,makeFighter,resolveCardAction,resolveBasic,resolveAutoBasic,afterAction,cloneFighter,bondMultiplier,supportBoost,isOffensive,applyPetRoundEnd,progressionStats} from '../src/cards.js';

const WORD_COUNT=800;
const SESSION_COOKIE='word_rpg_session';
const OAUTH_STATE_COOKIE='word_rpg_oauth_state';
const OAUTH_VERIFIER_COOKIE='word_rpg_oauth_verifier';
const OAUTH_NONCE_COOKIE='word_rpg_oauth_nonce';
const SESSION_SECONDS=60*60*24*30;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const qset=(used=[])=>{const blocked=new Set(used),out=[];while(out.length<3){const i=Math.floor(Math.random()*WORD_COUNT);if(!blocked.has(i)){blocked.add(i);out.push(i)}}return out};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const parseCookies=request=>Object.fromEntries((request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const at=x.indexOf('=');return at<0?[x,'']:[x.slice(0,at),decodeURIComponent(x.slice(at+1))]}));
const cookie=(name,value,maxAge)=>`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const clearCookie=name=>cookie(name,'',0);
const bytesToBase64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const textToBase64Url=text=>bytesToBase64Url(new TextEncoder().encode(text));
const base64UrlToText=value=>{const s=value.replace(/-/g,'+').replace(/_/g,'/'),p=s+'='.repeat((4-s.length%4)%4);return new TextDecoder().decode(Uint8Array.from(atob(p),c=>c.charCodeAt(0)))};
const randomToken=(length=32)=>{const bytes=new Uint8Array(length);crypto.getRandomValues(bytes);return bytesToBase64Url(bytes)};
async function sha256Base64Url(value){return bytesToBase64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))))}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return bytesToBase64Url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))))}
async function makeSession(profile,env){const secret=env.SESSION_SECRET||env.LINE_CHANNEL_SECRET;if(!secret)throw new Error('Missing session secret');const now=Math.floor(Date.now()/1000),payload={sub:profile.userId,name:profile.name||'LINE 玩家',picture:profile.picture||'',iat:now,exp:now+SESSION_SECONDS},encoded=textToBase64Url(JSON.stringify(payload)),sig=await hmac(secret,encoded);return `${encoded}.${sig}`}
async function readSession(request,env){const token=parseCookies(request)[SESSION_COOKIE];if(!token)return null;const [encoded,sig]=String(token).split('.');if(!encoded||!sig)return null;const secret=env.SESSION_SECRET||env.LINE_CHANNEL_SECRET;if(!secret)return null;const expected=await hmac(secret,encoded);if(sig!==expected)return null;try{const payload=JSON.parse(base64UrlToText(encoded));if(!payload.sub||!payload.exp||payload.exp<Math.floor(Date.now()/1000))return null;return payload}catch{return null}}
function callbackUrl(url,env){return env.LINE_CALLBACK_URL||`${url.origin}/auth/line/callback`}
function progressDefaults(){return {role:'warrior',pet:'fox',level:1,xp:0}}
function cleanProgress(input={}){const level=clamp(Math.round(Number(input.level)||1),1,50);return {role:['warrior','mage','archer'].includes(input.role)?input.role:'warrior',pet:['fox','owl','dragon'].includes(input.pet)?input.pet:'fox',level,xp:level>=50?0:Math.max(0,Math.round(Number(input.xp)||0))}}
async function userProgress(env,userId){const id=env.USER_STORE.idFromName(userId),stub=env.USER_STORE.get(id),res=await stub.fetch('https://user/progress');if(!res.ok)return progressDefaults();return cleanProgress(await res.json())}
async function saveUserProgress(env,userId,progress){const id=env.USER_STORE.idFromName(userId),stub=env.USER_STORE.get(id);return stub.fetch('https://user/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cleanProgress(progress))})}
async function beginLineLogin(request,env){if(!env.LINE_CHANNEL_ID||!env.LINE_CHANNEL_SECRET)return new Response('LINE Login 尚未設定：請先設定 LINE_CHANNEL_ID 與 LINE_CHANNEL_SECRET。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});const url=new URL(request.url),state=randomToken(),verifier=randomToken(48),nonce=randomToken(),challenge=await sha256Base64Url(verifier),redirect=callbackUrl(url,env),auth=new URL('https://access.line.me/oauth2/v2.1/authorize');auth.search=new URLSearchParams({response_type:'code',client_id:env.LINE_CHANNEL_ID,redirect_uri:redirect,state,scope:'openid profile',nonce,code_challenge:challenge,code_challenge_method:'S256'}).toString();const headers=new Headers({Location:auth.toString(),'Cache-Control':'no-store'});headers.append('Set-Cookie',cookie(OAUTH_STATE_COOKIE,state,600));headers.append('Set-Cookie',cookie(OAUTH_VERIFIER_COOKIE,verifier,600));headers.append('Set-Cookie',cookie(OAUTH_NONCE_COOKIE,nonce,600));return new Response(null,{status:302,headers})}
async function finishLineLogin(request,env){const url=new URL(request.url),cookies=parseCookies(request),state=url.searchParams.get('state'),code=url.searchParams.get('code');const fail=()=>Response.redirect(`${url.origin}/?line=error`,302);if(!code||!state||state!==cookies[OAUTH_STATE_COOKIE]||!cookies[OAUTH_VERIFIER_COOKIE])return fail();try{const redirect=callbackUrl(url,env),tokenRes=await fetch('https://api.line.me/oauth2/v2.1/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirect,client_id:env.LINE_CHANNEL_ID,client_secret:env.LINE_CHANNEL_SECRET,code_verifier:cookies[OAUTH_VERIFIER_COOKIE]})});if(!tokenRes.ok)return fail();const token=await tokenRes.json();if(!token.id_token)return fail();const verifyRes=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:token.id_token,client_id:env.LINE_CHANNEL_ID})});if(!verifyRes.ok)return fail();const verified=await verifyRes.json();if(!verified.sub||verified.nonce!==cookies[OAUTH_NONCE_COOKIE])return fail();let name=verified.name||'',picture=verified.picture||'';if((!name||!picture)&&token.access_token){const profileRes=await fetch('https://api.line.me/v2/profile',{headers:{Authorization:`Bearer ${token.access_token}`}});if(profileRes.ok){const profile=await profileRes.json();name=name||profile.displayName||'';picture=picture||profile.pictureUrl||''}}const session=await makeSession({userId:verified.sub,name,picture},env),headers=new Headers({Location:`${url.origin}/?line=1`,'Cache-Control':'no-store'});headers.append('Set-Cookie',cookie(SESSION_COOKIE,session,SESSION_SECONDS));headers.append('Set-Cookie',clearCookie(OAUTH_STATE_COOKIE));headers.append('Set-Cookie',clearCookie(OAUTH_VERIFIER_COOKIE));headers.append('Set-Cookie',clearCookie(OAUTH_NONCE_COOKIE));return new Response(null,{status:302,headers})}catch{return fail()}}
async function sessionApi(request,env){const session=await readSession(request,env);if(!session)return json({authenticated:false});const progress=await userProgress(env,session.sub);return json({authenticated:true,profile:{userId:session.sub,name:session.name,picture:session.picture||''},progress})}
async function progressApi(request,env){if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=new URL(request.url),origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Forbidden'},403);const session=await readSession(request,env);if(!session)return json({error:'Unauthorized'},401);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const progress=cleanProgress(body),res=await saveUserProgress(env,session.sub,progress);if(!res.ok)return json({error:'Save failed'},500);return json({ok:true,progress})}
function logout(request){const url=new URL(request.url),headers=new Headers({Location:url.origin+'/'});headers.append('Set-Cookie',clearCookie(SESSION_COOKIE));return new Response(null,{status:302,headers})}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/match'){const id=env.MATCHMAKER.idFromName('global-matchmaker');return env.MATCHMAKER.get(id).fetch(request)}if(url.pathname==='/auth/line')return beginLineLogin(request,env);if(url.pathname==='/auth/line/callback')return finishLineLogin(request,env);if(url.pathname==='/api/session')return sessionApi(request,env);if(url.pathname==='/api/progress')return progressApi(request,env);if(url.pathname==='/auth/logout')return logout(request);return env.ASSETS.fetch(request)}};

export class UserStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
  async fetch(request){if(request.method==='GET'){const progress=await this.ctx.storage.get('progress')||progressDefaults();return json(cleanProgress(progress))}if(request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const progress=cleanProgress(body);await this.ctx.storage.put('progress',progress);return json(progress)}return json({error:'Method not allowed'},405)}
}

export class Matchmaker extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
  async fetch(request){if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({id:crypto.randomUUID(),state:'new',profile:null,opponentId:null,matchId:null,fighter:null,hand:null,used:[],round:1,ready:null,questionUsed:[]});server.send(JSON.stringify({type:'connected'}));return new Response(null,{status:101,webSocket:client})}
  webSocketMessage(ws,message){let data;try{data=JSON.parse(typeof message==='string'?message:new TextDecoder().decode(message))}catch{return}if(data.type==='join')this.join(ws,data.profile||{});if(data.type==='ready')this.ready(ws,data)}
  profile(p){return {name:String(p.name||'PLAYER').slice(0,16),role:['warrior','mage','archer'].includes(p.role)?p.role:'warrior',pet:['fox','owl','dragon'].includes(p.pet)?p.pet:'fox',level:50}}
  send(ws,data){try{ws.send(JSON.stringify(data))}catch{}}
  find(id){return this.ctx.getWebSockets().find(x=>x.deserializeAttachment()?.id===id)}
  view(att){return {...cloneFighter(att.fighter),profile:att.profile}}
  join(ws,p){let att=ws.deserializeAttachment()||{};const profile=this.profile(p),stats=progressionStats(profile.role,profile.pet,profile.level).total;att={...att,state:'waiting',profile,fighter:makeFighter({...stats,role:profile.role,pet:profile.pet}),hand:dealHand(9,profile.role,profile.level),used:[],round:1,ready:null,questionUsed:[]};ws.serializeAttachment(att);const other=this.ctx.getWebSockets().find(x=>x!==ws&&x.deserializeAttachment()?.state==='waiting');if(!other){this.send(ws,{type:'queued'});return}let oa=other.deserializeAttachment();const matchId=crypto.randomUUID(),questions=qset([]);att={...att,state:'matched',opponentId:oa.id,matchId,questionUsed:[...questions]};oa={...oa,state:'matched',opponentId:att.id,matchId,questionUsed:[...questions]};ws.serializeAttachment(att);other.serializeAttachment(oa);this.send(ws,{type:'matched',self:this.view(att),opponent:this.view(oa),hand:att.hand,questions});this.send(other,{type:'matched',self:this.view(oa),opponent:this.view(att),hand:oa.hand,questions})}
  cleanReady(data,att){if(att.round>3)return {correct:0,elapsedMs:200,selected:[]};const correct=clamp(Math.round(Number(data.correct)||0),0,3),elapsedMs=clamp(Math.round(Number(data.elapsedMs)||30000),200,30000),available=att.hand.map((_,i)=>i).filter(i=>!att.used.includes(i));const selected=[...new Set((Array.isArray(data.selected)?data.selected:[]).map(Number).filter(i=>available.includes(i)))].slice(0,3);if(selected.length!==3)return null;return {correct,elapsedMs,selected}}
  ready(ws,data){let a=ws.deserializeAttachment();if(!a||a.state!=='matched'||a.ready)return;const ready=this.cleanReady(data,a);if(!ready){this.send(ws,{type:'error',message:'出牌資料錯誤'});return}a.ready=ready;ws.serializeAttachment(a);const other=this.find(a.opponentId);if(!other){this.send(ws,{type:'opponent-left'});return}let b=other.deserializeAttachment();if(!b?.ready){this.send(ws,{type:'waiting-opponent'});return}this.resolvePair(ws,a,other,b)}
  resolvePair(ws,a,other,b){
    const A=a.fighter,B=b.fighter,ra=a.ready,rb=b.ready,round=a.round,cardsA=round<=3?ra.selected.map(i=>a.hand[i]):[],cardsB=round<=3?rb.selected.map(i=>b.hand[i]):[],first=ra.elapsedMs<=rb.elapsedMs?'a':'b',sequence=[];
    if(first==='a')sequence.push('a','b','a','b','a','b');
    else sequence.push('b','a','b','a','b','a');
    const counts={a:0,b:0},stateA={pendingBoost:1,offensiveCount:0},stateB={pendingBoost:1,offensiveCount:0},stepsA=[],stepsB=[],allLogsA=[],allLogsB=[];
    const doCard=(actor,target,card,correct,pair,slot,state,speedWin)=>{const bond=bondMultiplier(pair,card);let boost=1;if(state.pendingBoost>1&&card?.id!=='boost'){boost=state.pendingBoost;state.pendingBoost=1}const offensiveIndex=state.offensiveCount,logs=resolveCardAction(actor,target,card,correct,{bond,boost,offensiveIndex,cards:pair,slotIndex:slot,speedWin});if(card?.id==='boost')state.pendingBoost=supportBoost(card,actor);if(isOffensive(card))state.offensiveCount++;afterAction(actor,target,logs);return logs};
    for(let i=0;i<sequence.length;i++){
      const who=sequence[i];if(A.hp<=0||B.hp<=0)break;const slot=counts[who]++;let logs=[],card=null;
      if(who==='a'){card=cardsA[slot];logs=doCard(A,B,card,ra.correct,cardsA,slot,stateA,first==='a')}
      else{card=cardsB[slot];logs=doCard(B,A,card,rb.correct,cardsB,slot,stateB,first==='b')}
      if(who==='a')allLogsA.push(...logs);else allLogsB.push(...logs);const cycle=null;
      stepsA.push({who:who==='a'?'self':'opponent',slot,cycle,finalRound:false,card,self:cloneFighter(A),opponent:cloneFighter(B),logs:[...logs]});
      stepsB.push({who:who==='b'?'self':'opponent',slot,cycle,finalRound:false,card,self:cloneFighter(B),opponent:cloneFighter(A),logs:[...logs]});
    }
    if(round<=3){const petLogsA=[],petLogsB=[];applyPetRoundEnd(A,cardsA,petLogsA);applyPetRoundEnd(B,cardsB,petLogsB);allLogsA.push(...petLogsA);allLogsB.push(...petLogsB);if(stepsA.length){stepsA[stepsA.length-1].logs.push(...petLogsA);stepsA[stepsA.length-1].self=cloneFighter(A);stepsA[stepsA.length-1].opponent=cloneFighter(B)}if(stepsB.length){stepsB[stepsB.length-1].logs.push(...petLogsB);stepsB[stepsB.length-1].self=cloneFighter(B);stepsB[stepsB.length-1].opponent=cloneFighter(A)}a.used.push(...ra.selected);b.used.push(...rb.selected)}
    a.fighter=A;b.fighter=B;const finished=round>=3||A.hp<=0||B.hp<=0;let winner=null,nextHandA=null,nextHandB=null;
    if(finished){const ar=A.hp/A.maxHp,br=B.hp/B.maxHp;winner=Math.abs(ar-br)<.0001?'draw':ar>br?'a':'b';a.state='finished';b.state='finished'}else{a.round++;b.round++;a.ready=null;b.ready=null}
    const nextQuestions=!finished&&round<3?qset(a.questionUsed||[]):null;if(nextQuestions){a.questionUsed=[...(a.questionUsed||[]),...nextQuestions];b.questionUsed=[...(b.questionUsed||[]),...nextQuestions]}
    ws.serializeAttachment(a);other.serializeAttachment(b);
    const orderText=first==='a'?`你先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`;
    this.send(ws,{type:'battle-result',round,self:this.view(a),opponent:this.view(b),correct:ra.correct,logs:allLogsA,steps:stepsA,opponentCards:cardsB,orderText,finished,winner:winner==='a'?'self':winner==='b'?'opponent':winner,nextQuestions,nextHand:nextHandA});
    this.send(other,{type:'battle-result',round,self:this.view(b),opponent:this.view(a),correct:rb.correct,logs:allLogsB,steps:stepsB,opponentCards:cardsA,orderText:first==='b'?`你先出手 · ${(rb.elapsedMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(ra.elapsedMs/1000).toFixed(1)} 秒`,finished,winner:winner==='b'?'self':winner==='a'?'opponent':winner,nextQuestions,nextHand:nextHandB})
  }
  webSocketClose(ws){const a=ws.deserializeAttachment();if(!a?.opponentId)return;const other=this.find(a.opponentId);if(other){this.send(other,{type:'opponent-left'});const b=other.deserializeAttachment();if(b){b.state='finished';other.serializeAttachment(b)}}}
  webSocketError(ws){this.webSocketClose(ws)}
}