export const ASSETS={
  role:{warrior:'/images/warrior.png',mage:'/images/mage.png',archer:'/images/archer.png'},
  roleAction:{warrior:['/images/warrior-act1.png','/images/warrior-act2.png'],mage:['/images/mage-act1.png','/images/mage-act2.png'],archer:['/images/archer-act1.png','/images/archer-act2.png']},
  pet:{fox:'/images/fox.png',owl:'/images/owl.png',dragon:'/images/dragon.png'},
  enemy:{moss:'/images/moss.png',rabbit:'/images/rabbit.png',bubble:'/images/bubble.png',beetle:'/images/beetle.png',shadowKing:'/images/shadow-king.png'},
  ui:{quest:'/images/Quest.png',achievement:'/images/Achievement.png',community:'/images/Community.png',equipment:'/images/equipment.png',fight:'/images/fight.png',pk:'/images/PK.png',petSkill:'/images/pet.png',tower:'/images/Test.png',collection:'/images/Compendium.png',back:'/images/return.png',vs:'/images/VS.png',confirm:'/images/confirm.png',victor:'/images/victor.png',fail:'/images/fail.png',levelUp:'/images/level%20up.png',hp:'/images/HP.png',atk:'/images/ATK.png',def:'/images/DEF.png',crit:'/images/Crit.png',shield:'/images/Shield.png'},
  card:{'stat-hp':'/images/card-stat-hp.png','stat-def':'/images/card-stat-def.png','stat-atk':'/images/card-stat-atk.png','stat-crit':'/images/card-stat-crit.png',combo:'/images/card-combo.png',desperate:'/images/card-desperate.png',poison:'/images/card-poison.png',break:'/images/card-break.png',sun:'/images/card-sun.png',preempt:'/images/card-preempt.png',regen:'/images/card-regen.png',sacrifice:'/images/card-sacrifice.png',restore:'/images/card-restore.png',diamond:'/images/card-diamond.png',aegis:'/images/card-aegis.png',boost:'/images/card-boost.png'},
  effect:{slash:'/images/effect-slash.png',crit:'/images/effect-crit.png',guard:'/images/effect-guard.png',heal:'/images/effect-heal.png'}
};
// Decode only the active role's two action frames ahead of combat to avoid hit-frame stalls on phones.
const decodedActions=new Map();
export function preloadRoleAction(role){
  if(typeof Image==='undefined')return Promise.resolve();
  if(decodedActions.has(role))return decodedActions.get(role);
  const frames=ASSETS.roleAction?.[role]||[];
  const pending=Promise.all(frames.map(src=>new Promise(resolve=>{
    const img=new Image();img.decoding='async';img.onload=()=>{if(img.decode)img.decode().then(resolve,resolve);else resolve()};img.onerror=resolve;img.src=src;
    if(img.complete&&img.naturalWidth)img.onload();
  })));
  decodedActions.set(role,pending);return pending;
}
function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function installCardAssetStyles(){if(typeof document==='undefined'||document.getElementById('card-asset-map'))return;const style=document.createElement('style');style.id='card-asset-map';style.textContent=Object.entries(ASSETS.card).map(([id,src])=>`.asset-slot[data-asset="card-${id}"]{background-image:url('${src}');background-size:contain;background-position:center;background-repeat:no-repeat;background-color:transparent;border:0;}`).join('\n');document.head.appendChild(style)}
function installSetupAssetStyles(){if(typeof document==='undefined'||document.getElementById('setup-asset-map'))return;const style=document.createElement('style');style.id='setup-asset-map';style.textContent=`.setup-card{grid-template-columns:repeat(3,minmax(0,1fr))!important;column-gap:14px!important;row-gap:16px!important}.setup-card>.choice-section{grid-column:1/-1}.setup-actions,.progression-actions{display:contents!important}.setup-actions>button,.progression-actions>.progression-btn{width:100%!important;height:118px!important;min-height:118px!important;padding:0!important;border:0!important;background-color:transparent!important;overflow:visible!important;align-self:stretch;display:grid!important;place-items:center!important}.setup-actions>button img{display:block!important;width:auto!important;height:98px!important;max-width:92%!important;max-height:98px!important;object-fit:contain!important;object-position:center!important}.progression-btn{background-position:center!important;background-repeat:no-repeat!important;background-size:auto 98px!important}.progression-btn>*{opacity:0!important;pointer-events:none!important}.setup-actions>[data-action="start"]{order:10}.setup-actions>[data-action="pk"]{order:11}.tower-entry{order:12;background-image:url('${ASSETS.ui.tower}')!important}.setup-actions>[data-action="pet-tree"]{order:13}.setup-actions>[data-action="equipment"]{order:14}.collection-entry{order:15;background-image:url('${ASSETS.ui.collection}')!important}.setup-actions>[data-action="quests"]{order:16}.setup-actions>[data-action="achievements"]{order:17}.setup-actions>[data-action="community"]{order:18}@media(max-width:700px){.setup-card{column-gap:8px!important;row-gap:10px!important}.setup-actions>button,.progression-actions>.progression-btn{height:96px!important;min-height:96px!important}.setup-actions>button img{height:80px!important;max-height:80px!important;max-width:92%!important}.progression-btn{background-size:auto 80px!important}}`;document.head.appendChild(style)}
installCardAssetStyles();installSetupAssetStyles();
export function visual(src,_fallback,className='art'){if(!src)return '';return `<span class="visual-wrap"><img class="${className}" src="${safeText(src)}" alt="" decoding="async" onerror="this.hidden=true"></span>`}
