import {ASSETS,visual} from './assets.js';
import {dealHand,makeFighter,resolveCardAction,resolveBasic,afterAction,cardSummary,cloneFighter,bondMultiplier,supportBoost,isOffensive,applyPetRoundEnd} from './cards.js';
import {createPkMode} from './pk.js';

const app=document.querySelector('#app');
const SAVE_KEY='word-rpg-card-v3';
const WORDS=[['apple','蘋果',['蘋果','香蕉','牛奶','麵包']],['book','書',['書','筆','桌子','門']],['cat','貓',['貓','狗','鳥','魚']],['run','跑步',['跑步','睡覺','坐下','吃飯']],['happy','開心的',['開心的','生氣的','疲累的','害怕的']],['water','水',['水','果汁','牛奶','茶']],['friend','朋友',['朋友','老師','醫生','學生']],['school','學校',['學校','公園','醫院','商店']],['green','綠色的',['綠色的','紅色的','藍色的','黃色的']],['small','小的',['小的','大的','高的','長的']],['river','河流',['河流','山','天空','森林']],['forest','森林',['森林','海洋','沙漠','城市']],['cloud','雲',['雲','雨','風','雪']],['quiet','安靜的',['安靜的','吵鬧的','快速的','明亮的']],['brave','勇敢的',['勇敢的','害怕的','疲累的','孤單的']],['follow','跟隨',['跟隨','離開','等待','停止']],['listen','聆聽',['聆聽','觀看','觸摸','奔跑']],['light','光',['光','影子','聲音','煙霧']],['path','小徑',['小徑','橋','房間','屋頂']],['rabbit','兔子',['兔子','狐狸','老虎','烏龜']],['protect','保護',['保護','攻擊','忘記','丟棄']],['whisper','低語',['低語','大叫','跳躍','哭泣']],['bridge','橋',['橋','道路','城堡','洞穴']],['stone','石頭',['石頭','木頭','葉子','花朵']],['deep','深的',['深的','淺的','短的','薄的']],['danger','危險',['危險','和平','秘密','希望']],['search','尋找',['尋找','隱藏','關閉','推動']],['across','穿越',['穿越','下面','旁邊','後面']],['sudden','突然的',['突然的','緩慢的','平靜的','柔軟的']],['bubble','泡泡',['泡泡','火焰','冰塊','沙子']]];
const ROLES={warrior:{name:'戰士',art:ASSETS.role.warrior,trait:'藍色牌 +30%，每張藍牌再獲得防禦力 20% 護盾'},mage:{name:'法師',art:ASSETS.role.mage,trait:'黃色牌 +25%，神功附體額外再 +20%'},archer:{name:'弓手',art:ASSETS.role.archer,trait:'紅色牌 +20%，連續攻擊牌第 2／3 張再 +15%／30%'}};
const PETS={fox:{name:'靈狐',art:ASSETS.pet.fox,trait:'搶到先手時第 1 張 +20%；2 張以上紅牌時，第 3 張後追加 40% 追擊'},owl:{name:'夜梟',art:ASSETS.pet.owl,trait:'全錯仍保留 25% 效果；2 張以上綠／藍牌時回合結束回復 8% 生命'},dragon:{name:'幼龍',art:ASSETS.pet.dragon,trait:'黃色牌 +20%；2 張以上黃牌時，最後一張再 +30%'}};
const STAGES=[{name:'苔球獸',art:ASSETS.enemy.moss,hp:430,atk:88,def:38,crit:.08},{name:'霧角兔',art:ASSETS.enemy.rabbit,hp:520,atk:100,def:48,crit:.12},{name:'木甲蟲',art:ASSETS.enemy.beetle,hp:620,atk:110,def:62,crit:.10},{name:'影語王',art:ASSETS.enemy.shadowKing,hp:760,atk:126,def:68,crit:.18}];
let meta=loadMeta(),screen='home',run=null,pkMode=null,actionTimer=null,selectTimeout=null,selectTicker=null,questionTimeout=null,questionTicker=null;
const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c};
const pick=a=>a[Math.floor(Math.random()*a.length)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function loadMeta(){try{return {...{playerName:'',role:'warrior',pet:'fox'},...JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')}}catch{return {playerName:'',role:'warrior',pet:'fox'}}}
function saveMeta(){localStorage.setItem(SAVE_KEY,JSON.stringify(meta))}
function q(){const w=pick(WORDS);return {word:w[0],answer:w[1],options:shuffle([...w[2]])}}
function questions(){return [q(),q(),q()]}
function stage(){return STAGES[run.stageIndex]}
function role(){return ROLES[meta.role]}
function clearTimers(){clearTimeout(actionTimer);clearTimeout(selectTimeout);clearInterval(selectTicker);clearTimeout(questionTimeout);clearInterval(questionTicker);actionTimer=selectTimeout=questionTimeout=null;selectTicker=questionTicker=null}
function openSetup(){const el=document.querySelector('#player-name'),name=(el?.value||meta.playerName||'').trim();if(!name){el?.focus();return}meta.playerName=name;saveMeta();screen='setup';render()}
function startRun(){clearTimers();run={stageIndex:0,player:makeFighter({role:meta.role,pet:meta.pet}),enemy:null,round:1,hand:dealHand(9),enemyHand:dealHand(9),used:[],enemyUsed:[],selected:[],enemySelected:[],correct:0,qIndex:0,qs:[],quizStarted:0,questionDeadline:0,selectDeadline:0,log:[],lastOrder:'',steps:[],stepIndex:0,actionStartPlayer:null,actionStartEnemy:null};beginStage()}
function beginStage(){clearTimers();const s=stage();run.player.role=meta.role;run.player.pet=meta.pet;run.enemy=makeFighter({role:'monster',pet:null,maxHp:s.hp,hp:s.hp,atk:s.atk,def:s.def,crit:s.crit});run.round=1;run.hand=dealHand(9);run.enemyHand=dealHand(9);run.used=[];run.enemyUsed=[];run.selected=[];run.enemySelected=[];run.log=[];run.steps=[];run.selectDeadline=0;screen='cards';render()}
function startPk(){clearTimers();pkMode?.stop(false);pkMode=createPkMode({app,meta,ROLES,PETS,WORDS,visual,effects:ASSETS.effect,onExit:()=>{pkMode=null;screen='setup';render()}});pkMode.start()}
function slot(id){return `<span class="asset-slot" data-asset="${esc(id)}"></span>`}
function renderHome(){return `<main class="home-screen"><section class="home-panel home-login"><input id="player-name" value="${esc(meta.playerName)}" maxlength="16" placeholder="輸入名字"><button class="line-image-btn" data-action="line-login" aria-label="LINE 登入"></button></section><button class="fight-hotspot" data-action="setup" aria-label="進入遊戲"></button></main>`}
function renderSetup(){return `<main class="setup-screen"><section class="setup-card"><h1>選擇角色</h1><div class="pick-grid">${Object.entries(ROLES).map(([id,x])=>`<button class="pick-card ${meta.role===id?'active':''}" data-role="${id}">${visual(x.art,'','pick-art')}<b>${x.name}</b><small>${esc(x.trait)}</small></button>`).join('')}</div><h1>選擇夥伴</h1><div class="pick-grid pets">${Object.entries(PETS).map(([id,x])=>`<button class="pick-card ${meta.pet===id?'active':''}" data-pet="${id}">${visual(x.art,'','pick-art')}<b>${x.name}</b><small>${esc(x.trait)}</small></button>`).join('')}</div><div class="setup-actions"><button class="primary-btn" data-action="start">開始冒險</button><button class="secondary-btn" data-action="pk">線上對戰</button></div></section></main>`}
function stats(f){return `<div class="stat-row"><span>生命 ${Math.max(0,Math.round(f.hp))}/${Math.round(f.maxHp)}</span><span>攻擊 ${Math.round(f.atk)}</span><span>防禦 ${Math.round(f.def)}</span><span>爆擊 ${Math.round(f.crit*100)}%</span>${f.shield>0?`<span>護盾 ${Math.round(f.shield)}</span>`:''}</div>`}
function selectedCardsHtml(cards=[],active=-1,enemy=false){if(!cards.length)return '';return `<div class="selected-action-cards ${enemy?'enemy-cards':''}">${cards.map((c,i)=>`<div class="mini-card ${c.color} ${i===active?'active':''}">${slot('card-'+c.id)}<b>${esc(c.name)}</b><span>${i+1}</span></div>`).join('')}</div>`}
function actionVisual(step,prevP,prevE,p,e){if(!step)return null;const mine=step.who==='player',card=step.card,actorPrev=mine?prevP:prevE,actorNow=mine?p:e,targetPrev=mine?prevE:prevP,targetNow=mine?e:p,logs=step.logs||[];const damage=Math.max(0,Math.round((targetPrev?.hp||0)-(targetNow?.hp||0))),heal=Math.max(0,Math.round((actorNow?.hp||0)-(actorPrev?.hp||0))),shield=Math.max(0,Math.round((actorNow?.shield||0)-(actorPrev?.shield||0))),crit=logs.some(x=>String(x).includes('爆擊'));let kind='slash',self=false;if(heal>0||card?.id==='restore'||card?.id==='regen'||card?.stat==='hp'){kind='heal';self=true}else if(shield>0||card?.id==='diamond'||card?.id==='aegis'||card?.stat==='def'){kind='guard';self=true}else if(crit||card?.id==='sacrifice')kind='crit';else if(card&&!isOffensive(card)){kind='guard';self=true}const amount=heal>0?`+${heal}`:shield>0?`+${shield}`:damage>0?`-${damage}`:'';return {kind,self,amount,crit,mine}}
function combatHeader({playerState=run.player,enemyState=run.enemy,activeStep=null,showChosen=false,visualMeta=null}={}){const s=stage(),php=clamp(playerState.hp/playerState.maxHp*100,0,100),ehp=clamp(enemyState.hp/enemyState.maxHp*100,0,100),pc=run.round<3?run.selected.map(i=>run.hand[i]):[],ec=run.round<3?run.enemySelected.map(i=>run.enemyHand[i]):[],heroAct=activeStep?.who==='player',enemyAct=activeStep?.who==='enemy',selfFx=visualMeta?.self,fxOnHero=visualMeta&&(selfFx?heroAct:enemyAct),fxOnEnemy=visualMeta&&(selfFx?enemyAct:heroAct),effect=visualMeta?.kind?ASSETS.effect[visualMeta.kind]:null;return `<header class="battle-top"><button class="text-btn" data-action="quit">返回</button><b>第 ${run.round} 回合</b><span>${run.stageIndex+1}/${STAGES.length}</span></header><section class="combat-stage focus-stage ${activeStep?'impact-stage':''} ${visualMeta?.crit?'critical-stage':''}"><div class="fighter hero ${heroAct?'is-acting':''} ${enemyAct&&!selfFx?'is-hit':''}">${visual(role().art,'','fighter-art')}<div class="name-line">${esc(meta.playerName)}</div><div class="hp"><i style="width:${php}%"></i></div>${stats(playerState)}${fxOnHero&&effect?`<img class="battle-effect ${visualMeta.kind}" src="${effect}" alt="">`:''}${fxOnHero&&visualMeta.amount?`<span class="impact-number ${visualMeta.kind}">${visualMeta.amount}</span>`:''}</div><div class="battle-center"><strong>${activeStep?esc(activeStep.who==='player'?'我方行動':'敵方行動'):'VS'}</strong><small>${run.round<3?'一張卡＝一次出手':'最終回合'}</small></div><div class="fighter enemy ${enemyAct?'is-acting':''} ${heroAct&&!selfFx?'is-hit':''}">${visual(s.art,'','fighter-art')}<div class="name-line">${esc(s.name)}</div><div class="hp enemy-hp"><i style="width:${ehp}%"></i></div>${stats(enemyState)}${fxOnEnemy&&effect?`<img class="battle-effect ${visualMeta.kind}" src="${effect}" alt="">`:''}${fxOnEnemy&&visualMeta.amount?`<span class="impact-number ${visualMeta.kind}">${visualMeta.amount}</span>`:''}</div>${showChosen?`<div class="combat-card-rail player-rail">${selectedCardsHtml(pc,activeStep?.who==='player'?activeStep.slot:-1,false)}</div><div class="combat-card-rail enemy-rail">${selectedCardsHtml(ec,activeStep?.who==='enemy'?activeStep.slot:-1,true)}</div>`:''}</section>`}
function cardHtml(c,i){const used=run.used.includes(i),order=run.selected.indexOf(i)+1;return `<button class="battle-card ${c.color} ${used?'used':''} ${order?'selected':''}" data-card="${i}" ${used?'disabled':''}><span class="card-order">${order||''}</span>${slot('card-'+c.id)}<b>${esc(c.name)}</b><small>${c.kind==='stat'?`增加 ${c.pct}%`:c.id==='boost'?`下一張卡 +${c.boost}%`:esc(c.text)}</small></button>`}
function ensureSelectionTimer(){if(screen!=='cards'||run.round>=3)return;if(!run.selectDeadline)run.selectDeadline=Date.now()+60000;clearTimeout(selectTimeout);clearInterval(selectTicker);selectTimeout=setTimeout(()=>{if(screen!=='cards')return;autoFillSelection();confirmCards(true)},Math.max(0,run.selectDeadline-Date.now()));selectTicker=setInterval(()=>{const el=document.querySelector('[data-select-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((run.selectDeadline-Date.now())/1000)))},250)}
function renderCards(){queueMicrotask(ensureSelectionTimer);return `<main class="battle-screen">${combatHeader()}<section class="card-zone"><div class="section-title"><h1>依順序選 3 張</h1><p>剩餘 <b data-select-time>${Math.max(0,Math.ceil(((run.selectDeadline||Date.now()+60000)-Date.now())/1000))}</b> 秒　未完成會自動隨機補滿</p></div><div class="hand-grid">${run.hand.map(cardHtml).join('')}</div><button class="primary-btn confirm-cards" data-action="confirm-cards" ${run.selected.length!==3?'disabled':''}>確認出牌</button></section></main>`}
function autoFillSelection(){const available=run.hand.map((_,i)=>i).filter(i=>!run.used.includes(i)&&!run.selected.includes(i));while(run.selected.length<3&&available.length)run.selected.push(available.splice(Math.floor(Math.random()*available.length),1)[0])}
function confirmCards(auto=false){if(run.selected.length!==3){if(!auto)return;autoFillSelection()}if(run.selected.length!==3)return;clearTimeout(selectTimeout);clearInterval(selectTicker);run.selectDeadline=0;run.enemySelected=aiPickIndices();startQuiz()}
function startQuiz(){run.correct=0;run.qIndex=0;run.qs=questions();run.quizStarted=performance.now();screen='quiz';render();startQuestionTimer()}
function startQuestionTimer(){clearTimeout(questionTimeout);clearInterval(questionTicker);run.questionDeadline=Date.now()+10000;questionTimeout=setTimeout(()=>answer(null,true),10000);questionTicker=setInterval(()=>{const el=document.querySelector('[data-question-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((run.questionDeadline-Date.now())/1000)))},200)}
function answer(value,timedOut=false){const cur=run.qs[run.qIndex];if(!cur||screen!=='quiz')return;clearTimeout(questionTimeout);clearInterval(questionTicker);if(!timedOut&&value===cur.answer)run.correct++;run.qIndex++;if(run.qIndex>=3){const elapsed=Math.min(30000,Math.max(1,Math.round(performance.now()-run.quizStarted)));resolveRound(elapsed);return}render();startQuestionTimer()}
function renderQuiz(){const cur=run.qs[run.qIndex];return `<main class="battle-screen combat-focus">${combatHeader({showChosen:true})}<section class="quiz-zone compact-quiz"><div class="quiz-progress">${run.qIndex+1} / 3　剩餘 <b data-question-time>${Math.max(0,Math.ceil(((run.questionDeadline||Date.now()+10000)-Date.now())/1000))}</b> 秒</div><h1>${esc(cur.word)}</h1><div class="answer-grid">${cur.options.map(o=>`<button class="answer-btn" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div></section></main>`}
function aiPickIndices(){return shuffle(run.enemyHand.map((_,i)=>i).filter(i=>!run.enemyUsed.includes(i))).slice(0,3)}
function playerCards(){return run.selected.map(i=>run.hand[i])}function enemyCards(){return run.enemySelected.map(i=>run.enemyHand[i])}
function executeCard(actor,target,card,correct,pair,slotIndex,state,speedWin){const bond=bondMultiplier(pair,card);let boost=1;if(state.pendingBoost>1&&card.id!=='boost'){boost=state.pendingBoost;state.pendingBoost=1}const logs=resolveCardAction(actor,target,card,correct,{bond,boost,offensiveIndex:state.offensiveCount,cards:pair,slotIndex,speedWin});if(card.id==='boost')state.pendingBoost=supportBoost(card,actor);if(isOffensive(card))state.offensiveCount++;afterAction(actor,target,logs);return logs}
function resolveRound(playerMs){clearTimeout(questionTimeout);clearInterval(questionTicker);const pc=run.round<3?playerCards():[],ec=run.round<3?enemyCards():[],enemyCorrect=pick([1,2,2,3,3]),enemyMs=4000+Math.floor(Math.random()*22000),first=playerMs<=enemyMs?'player':'enemy';if(run.round<3){run.used.push(...run.selected);run.enemyUsed.push(...run.enemySelected)}const P=run.player,E=run.enemy,ps={pendingBoost:1,offensiveCount:0},es={pendingBoost:1,offensiveCount:0},sequence=[];run.actionStartPlayer=cloneFighter(P);run.actionStartEnemy=cloneFighter(E);if(run.round===3)sequence.push(first,first==='player'?'enemy':'player');else if(first==='player')sequence.push('player','enemy','player','enemy','player','enemy');else sequence.push('enemy','player','enemy','player','enemy','player');const counts={player:0,enemy:0},steps=[];for(const who of sequence){if(P.hp<=0||E.hp<=0)break;const slot=counts[who]++;let logs=[];if(run.round===3){logs=who==='player'?resolveBasic(P,E,run.correct):resolveBasic(E,P,enemyCorrect);afterAction(who==='player'?P:E,who==='player'?E:P,logs)}else if(who==='player')logs=executeCard(P,E,pc[slot],run.correct,pc,slot,ps,first==='player');else logs=executeCard(E,P,ec[slot],enemyCorrect,ec,slot,es,first==='enemy');steps.push({who,slot,card:run.round<3?(who==='player'?pc[slot]:ec[slot]):null,logs:[...logs],player:cloneFighter(P),enemy:cloneFighter(E)})}if(run.round<3&&P.hp>0){const petLogs=[];applyPetRoundEnd(P,pc,petLogs);if(petLogs.length&&steps.length){steps[steps.length-1].logs.push(...petLogs);steps[steps.length-1].player=cloneFighter(P)}}run.lastOrder=first==='player'?`你先出手 · ${(playerMs/1000).toFixed(1)} 秒`:`對手先出手 · ${(enemyMs/1000).toFixed(1)} 秒`;run.steps=steps;run.stepIndex=0;run.enemyCorrect=enemyCorrect;run.log=steps.flatMap(s=>s.logs).slice(-16);screen='action';render();scheduleActionStep()}
function stepDelay(){const step=run.steps[run.stepIndex];if(step?.who==='player'&&meta.role==='archer'&&isOffensive(step.card))return Math.max(620,920-step.slot*120);if(step?.card?.id==='sacrifice')return 1250;return 980}
function scheduleActionStep(){clearTimeout(actionTimer);actionTimer=setTimeout(()=>{if(screen!=='action')return;if(run.stepIndex<run.steps.length-1){run.stepIndex++;render();scheduleActionStep()}else actionTimer=setTimeout(()=>{screen='resolve';render()},500)},stepDelay())}
function renderAction(){const step=run.steps[run.stepIndex],prev=run.stepIndex>0?run.steps[run.stepIndex-1]:null,prevP=prev?.player||run.actionStartPlayer,prevE=prev?.enemy||run.actionStartEnemy,p=step?.player||run.player,e=step?.enemy||run.enemy,metaFx=actionVisual(step,prevP,prevE,p,e);return `<main class="battle-screen combat-focus action-screen">${combatHeader({playerState:p,enemyState:e,activeStep:step,showChosen:true,visualMeta:metaFx})}<section class="action-status"><h1>${step?.card?esc(cardSummary(step.card)):'基本攻擊'}</h1><div class="battle-log current-log">${(step?.logs||[]).slice(-3).map(x=>`<p>${esc(x)}</p>`).join('')}</div></section></main>`}
function renderResolve(){const quality=run.correct===3?'150%':run.correct===2?'100%':run.correct===1?'50%':'0%';return `<main class="battle-screen combat-focus">${combatHeader({showChosen:true})}<section class="resolve-zone"><h1>${esc(run.lastOrder)}</h1><div class="result-power">答對 ${run.correct}/3 · 效果 ${quality}</div><div class="battle-log">${run.log.map(x=>`<p>${esc(x)}</p>`).join('')}</div><button class="primary-btn" data-action="next-round">${run.round>=3?'查看結果':'下一回合'}</button></section></main>`}
function nextRound(){if(run.player.hp<=0||run.enemy.hp<=0||run.round>=3)return finishBattle();run.round++;run.selected=[];run.enemySelected=[];run.selectDeadline=0;if(run.round===3){startQuiz();return}screen='cards';render()}
function finishBattle(){const p=run.player.hp/run.player.maxHp,e=run.enemy.hp/run.enemy.maxHp,win=run.enemy.hp<=0||(run.player.hp>0&&p>=e);if(!win){screen='lose';render();return}if(run.stageIndex>=STAGES.length-1){screen='win';render();return}run.player.hp=Math.min(run.player.maxHp,run.player.hp+Math.round(run.player.maxHp*.2));run.player.poison=[];run.player.armorBreak=[];run.player.atkDown=[];run.player.defBoost=[];run.player.critLock=0;run.stageIndex++;screen='stage-clear';render()}
function renderStageClear(){return `<main class="result-screen"><section class="result-card"><h1>勝利</h1><p>保留養成能力，下一戰重新發 9 張牌。</p><button class="primary-btn" data-action="next-stage">下一戰</button></section></main>`}
function renderResult(win){return `<main class="result-screen"><section class="result-card"><h1>${win?'完成冒險':'挑戰失敗'}</h1><button class="primary-btn" data-action="retry">重新開始</button><button class="secondary-btn" data-action="home">回首頁</button></section></main>`}
function render(){app.innerHTML=screen==='home'?renderHome():screen==='setup'?renderSetup():screen==='cards'?renderCards():screen==='quiz'?renderQuiz():screen==='action'?renderAction():screen==='resolve'?renderResolve():screen==='stage-clear'?renderStageClear():screen==='win'?renderResult(true):screen==='lose'?renderResult(false):renderHome();bind()}
function bind(){document.querySelector('[data-action="setup"]')?.addEventListener('click',openSetup);document.querySelector('[data-action="start"]')?.addEventListener('click',startRun);document.querySelector('[data-action="pk"]')?.addEventListener('click',startPk);document.querySelector('[data-action="quit"]')?.addEventListener('click',()=>{clearTimers();screen='setup';render()});document.querySelector('[data-action="confirm-cards"]')?.addEventListener('click',()=>confirmCards(false));document.querySelector('[data-action="next-round"]')?.addEventListener('click',nextRound);document.querySelector('[data-action="next-stage"]')?.addEventListener('click',beginStage);document.querySelector('[data-action="retry"]')?.addEventListener('click',startRun);document.querySelector('[data-action="home"]')?.addEventListener('click',()=>{clearTimers();screen='home';render()});document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{meta.role=b.dataset.role;saveMeta();render()}));document.querySelectorAll('[data-pet]').forEach(b=>b.addEventListener('click',()=>{meta.pet=b.dataset.pet;saveMeta();render()}));document.querySelectorAll('[data-card]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.card);if(run.used.includes(i))return;const at=run.selected.indexOf(i);if(at>=0)run.selected.splice(at,1);else if(run.selected.length<3)run.selected.push(i);render()}));document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.answer,false)))}
render();
