import {ASSETS,visual} from './assets.js';
import {WORDS,makeQuestion,wordDeck} from './words.js';
import {dealHand,makeFighter,resolveCardAction,resolveBasic,resolveAutoBasic,afterAction,cardSummary,cloneFighter,bondMultiplier,supportBoost,isOffensive,applyPetRoundEnd,progressionStats} from './cards.js';
import {createPkMode} from './pk.js';

const app=document.querySelector('#app');
const SAVE_KEY='word-rpg-card-v3';
const ROLES={warrior:{name:'戰士',art:ASSETS.role.warrior,trait:'藍牌更強，出牌時還能補護盾'},mage:{name:'法師',art:ASSETS.role.mage,trait:'黃牌更強，神功附體效果更高'},archer:{name:'弓手',art:ASSETS.role.archer,trait:'紅牌更強，連續攻擊越打越痛'}};
const PETS={fox:{name:'靈狐',art:ASSETS.pet.fox,trait:'搶到先手更強；紅牌多時會追擊'},owl:{name:'夜梟',art:ASSETS.pet.owl,trait:'答錯仍有保底；防守牌多時會回血'},dragon:{name:'幼龍',art:ASSETS.pet.dragon,trait:'黃牌更強；連用黃牌會再爆發'}};
const STAGES=[
  {id:'moss',name:'苔球獸',art:ASSETS.enemy.moss,hp:560,atk:105,def:48,crit:.10,skill:'孢子甲殼',skillText:'每回合獲得護盾，毒素傷害減半'},
  {id:'rabbit',name:'霧角兔',art:ASSETS.enemy.rabbit,hp:660,atk:120,def:55,crit:.16,skill:'霧影突襲',skillText:'更容易搶先手，連擊後兩段減傷'},
  {id:'beetle',name:'木甲蟲',art:ASSETS.enemy.beetle,hp:800,atk:132,def:78,crit:.12,skill:'硬殼反震',skillText:'每回合獲得護盾，受到攻擊會反震'},
  {id:'shadow',name:'影語王',art:ASSETS.enemy.shadowKing,hp:1000,atk:155,def:85,crit:.22,skill:'暗影汲取',skillText:'攻擊吸血，半血狂暴並清除負面'}
];
const CARD_HINT={combo:'3次連擊\n每擊 50%',desperate:'重擊 200%\n自身降防',poison:'傷害\n中毒 3回合',break:'傷害\n降防 2回合',sun:'傷害\n封鎖爆擊 2回合',preempt:'傷害\n降攻 2回合',regen:'立即回血\n持續回血',sacrifice:'超高傷害\n消耗生命',restore:'大量回血\n溢出護盾',diamond:'防禦提升\n持續 2回合',aegis:'獲得護盾\n戰鬥期間有效',boost:'強化下張牌\n立即護盾'};
const TITLE_STEPS=[[30,'傳說勇者'],[20,'菁英勇者'],[10,'覺醒勇者'],[5,'冒險者'],[1,'初行者']];
let meta=loadMeta(),screen='home',run=null,pkMode=null,actionTimer=null,selectTimeout=null,selectTicker=null,questionTimeout=null,questionTicker=null,answerFeedback=null;
const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c};
const pick=a=>a[Math.floor(Math.random()*a.length)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadMeta(){const base={playerName:'',role:'warrior',pet:'fox',level:1,xp:0};try{const x={...base,...JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')};x.level=Math.max(1,Math.min(50,Math.round(Number(x.level)||1)));x.xp=Math.max(0,Math.round(Number(x.xp)||0));return x}catch{return base}}
function saveMeta(){localStorage.setItem(SAVE_KEY,JSON.stringify(meta))}
function xpNeed(level=meta.level){return 120+Math.max(0,level-1)*80}
function titleFor(level=meta.level){return TITLE_STEPS.find(([lv])=>level>=lv)?.[1]||'初行者'}
function addXp(amount){const old=meta.level,levels=[];meta.xp+=Math.max(0,Math.round(amount));while(meta.level<50&&meta.xp>=xpNeed(meta.level)){meta.xp-=xpNeed(meta.level);meta.level++;levels.push(meta.level)}saveMeta();return {amount,old,newLevel:meta.level,levels,title:titleFor(meta.level)}}
function growth(){return progressionStats(meta.role,meta.pet,meta.level)}
function growthItem(src,value,label){return `<span class="growth-stat" title="${esc(label)}">${uiImg(src,label,'')}<b>${esc(value)}</b></span>`}
function growthPanel(stats){return `<div class="growth-panel"><div class="growth-level"><b>Lv.${meta.level}</b><span>${esc(titleFor(meta.level))}</span></div><div class="growth-stats">${growthItem(ASSETS.ui.hp,stats.maxHp,'生命')}${growthItem(ASSETS.ui.atk,stats.atk,'攻擊')}${growthItem(ASSETS.ui.def,stats.def,'防禦')}</div></div>`}
function q(){if(!run.wordDeck?.length)run.wordDeck=wordDeck();return makeQuestion(run.wordDeck.pop())}
function questions(){return [q(),q(),q()]}
function rawStage(){return STAGES[run.stageIndex]}
function stage(){const s=rawStage(),lv=run?.level||meta.level,hp=1+(lv-1)*.055,atk=1+(lv-1)*.035,def=1+(lv-1)*.03;let extra='';if(lv>=10){if(s.id==='moss')extra='；低血量會再生';if(s.id==='rabbit')extra='；後段會再突襲';if(s.id==='beetle')extra='；反震更強';if(s.id==='shadow')extra='；吸血與狂暴強化'}return {...s,hp:Math.round(s.hp*hp),atk:Math.round(s.atk*atk),def:Math.round(s.def*def),skillText:s.skillText+extra}}
function role(){return ROLES[meta.role]}
function clearTimers(){clearTimeout(actionTimer);clearTimeout(selectTimeout);clearInterval(selectTicker);clearTimeout(questionTimeout);clearInterval(questionTicker);actionTimer=selectTimeout=questionTimeout=null;selectTicker=questionTicker=null}
function openSetup(){const el=document.querySelector('#player-name'),name=(el?.value||meta.playerName||'').trim();if(!name){el?.focus();return}meta.playerName=name;saveMeta();screen='setup';render()}
function freshStats(){return {correct:0,total:0,damage:0,heal:0}}
function startRun(){clearTimers();answerFeedback=null;const p=progressionStats(meta.role,meta.pet,meta.level).total;run={level:meta.level,stageIndex:0,player:makeFighter({...p,role:meta.role,pet:meta.pet}),enemy:null,round:1,hand:dealHand(9),enemyHand:dealHand(9),used:[],enemyUsed:[],selected:[],enemySelected:[],correct:0,qIndex:0,qs:[],quizStarted:0,questionDeadline:0,selectDeadline:0,log:[],lastOrder:'',steps:[],stepIndex:0,actionStartPlayer:null,actionStartEnemy:null,stats:freshStats(),wrongAnswers:[],wordDeck:wordDeck(),stageRewarded:false,lastReward:null};beginStage()}
function beginStage(){clearTimers();answerFeedback=null;const s=stage();run.player.role=meta.role;run.player.pet=meta.pet;run.enemy=makeFighter({role:'monster',pet:null,monsterId:s.id,maxHp:s.hp,hp:s.hp,atk:s.atk,def:s.def,crit:s.crit});run.enemy.enraged=false;run.round=1;run.hand=dealHand(9);run.enemyHand=dealHand(9);run.used=[];run.enemyUsed=[];run.selected=[];run.enemySelected=[];run.log=[];run.steps=[];run.selectDeadline=0;run.stageRewarded=false;run.lastReward=null;screen='cards';render()}
function startPk(){clearTimers();pkMode?.stop(false);pkMode=createPkMode({app,meta,ROLES,PETS,visual,effects:ASSETS.effect,onExit:()=>{pkMode=null;screen='setup';render()}});pkMode.start()}
function slot(id){return `<span class="asset-slot" data-asset="${esc(id)}"></span>`}
function uiImg(src,label,style=''){return `<img src="${esc(src)}" alt="${esc(label)}" style="${style}" decoding="async">`}
function imageButton(src,label,attrs=''){return `<button ${attrs} aria-label="${esc(label)}" style="border:0;background:transparent;padding:0;display:grid;place-items:center;width:100%;cursor:pointer">${uiImg(src,label,'display:block;max-width:100%;height:auto;object-fit:contain;')}</button>`}
function renderHome(){return `<main class="home-screen"><section class="home-panel home-login"><input id="player-name" value="${esc(meta.playerName)}" maxlength="16" placeholder="輸入名字"><button class="line-image-btn" data-action="line-login" aria-label="LINE 登入"></button></section><button class="fight-hotspot" data-action="setup" aria-label="進入遊戲"></button></main>`}
function renderSetup(){const r=ROLES[meta.role]||ROLES.warrior,p=PETS[meta.pet]||PETS.fox,g=growth();return `<main class="setup-screen"><section class="setup-card"><section class="choice-section"><div class="choice-feature role-feature theme-${esc(meta.role)} growth-feature"><div class="growth-art role-growth-art">${uiImg(r.art,r.name,'')}</div>${growthPanel(g.role)}</div><div class="choice-tabs">${Object.entries(ROLES).map(([id,x])=>`<button class="choice-tab ${meta.role===id?'active':''}" data-role="${id}">${esc(x.name)}</button>`).join('')}</div></section><section class="choice-section pet-section"><div class="choice-feature pet-feature theme-${esc(meta.pet)} growth-feature"><div class="growth-art pet-growth-art">${uiImg(p.art,p.name,'')}</div>${growthPanel(g.pet)}</div><div class="choice-tabs">${Object.entries(PETS).map(([id,x])=>`<button class="choice-tab ${meta.pet===id?'active':''}" data-pet="${id}">${esc(x.name)}</button>`).join('')}</div></section><div class="setup-actions">${imageButton(ASSETS.ui.fight,'開始冒險','data-action="start"')}${imageButton(ASSETS.ui.pk,'線上對戰','data-action="pk"')}</div></section></main>`}
function statItem(src,value,label){return `<span title="${esc(label)}" style="display:inline-flex;align-items:center;gap:7px">${uiImg(src,label,'width:34px;height:34px;object-fit:contain;flex:0 0 auto;')}<b style="font-size:20px;line-height:1">${esc(value)}</b></span>`}
function stats(f){return `<div class="stat-row">${statItem(ASSETS.ui.hp,`${Math.max(0,Math.round(f.hp))}/${Math.round(f.maxHp)}`,'生命')}${statItem(ASSETS.ui.atk,Math.round(f.atk),'攻擊')}${statItem(ASSETS.ui.def,Math.round(f.def),'防禦')}${statItem(ASSETS.ui.crit,`${Math.round(f.crit*100)}%`,'爆擊')}${f.shield>0?`<span>護盾 ${Math.round(f.shield)}</span>`:''}</div>`}
function selectedCardsHtml(cards=[],active=-1,enemy=false){if(!cards.length)return '';return `<div class="selected-action-cards ${enemy?'enemy-cards':''}">${cards.map((c,i)=>`<div class="mini-card ${c.color} ${i===active?'active':''}">${slot('card-'+c.id)}<b>${esc(c.name)}</b><span>${i+1}</span></div>`).join('')}</div>`}
function actionVisual(step,prevP,prevE,p,e){if(!step)return null;const mine=step.who==='player',card=step.card,actorPrev=mine?prevP:prevE,actorNow=mine?p:e,targetPrev=mine?prevE:prevP,targetNow=mine?e:p,logs=step.logs||[];const damage=Math.max(0,Math.round((targetPrev?.hp||0)-(targetNow?.hp||0))),heal=Math.max(0,Math.round((actorNow?.hp||0)-(actorPrev?.hp||0))),shield=Math.max(0,Math.round((actorNow?.shield||0)-(actorPrev?.shield||0))),crit=logs.some(x=>String(x).includes('爆擊'));let kind='slash',self=false;if(heal>0||card?.id==='restore'||card?.id==='regen'||card?.stat==='hp'){kind='heal';self=true}else if(shield>0||card?.id==='diamond'||card?.id==='aegis'||card?.stat==='def'){kind='guard';self=true}else if(crit||card?.id==='sacrifice')kind='crit';else if(card&&!isOffensive(card)){kind='guard';self=true}const amount=heal>0?`+${heal}`:shield>0?`+${shield}`:damage>0?`-${damage}`:'';return {kind,self,amount,crit,mine}}
function combatHeader({playerState=run.player,enemyState=run.enemy,activeStep=null,showChosen=false,visualMeta=null}={}){const s=stage(),php=clamp(playerState.hp/playerState.maxHp*100,0,100),ehp=clamp(enemyState.hp/enemyState.maxHp*100,0,100),pc=run.round<3?run.selected.map(i=>run.hand[i]):[],ec=run.round<3?run.enemySelected.map(i=>run.enemyHand[i]):[],heroAct=activeStep?.who==='player',enemyAct=activeStep?.who==='enemy',selfFx=visualMeta?.self,fxOnHero=visualMeta&&(selfFx?heroAct:enemyAct),fxOnEnemy=visualMeta&&(selfFx?enemyAct:heroAct),effect=visualMeta?.kind?ASSETS.effect[visualMeta.kind]:null,stagePadding=showChosen&&run.round<3?'':'padding-bottom:30px;';return `<header class="battle-top"><button data-action="quit" aria-label="返回" style="border:0;background:transparent;padding:0;justify-self:start;width:112px">${uiImg(ASSETS.ui.back,'返回','display:block;width:100%;height:auto;object-fit:contain;')}</button><span></span><span>${run.stageIndex+1}/${STAGES.length}</span></header><section class="combat-stage focus-stage ${activeStep?'impact-stage':''} ${visualMeta?.crit?'critical-stage':''}" style="${stagePadding}"><div class="fighter hero ${heroAct?'is-acting':''} ${enemyAct&&!selfFx?'is-hit':''}">${visual(role().art,'','fighter-art')}<div class="name-line">${esc(meta.playerName)}</div><div class="hp"><i style="width:${php}%"></i></div>${stats(playerState)}${fxOnHero&&effect?`<img class="battle-effect ${visualMeta.kind}" src="${effect}" alt="">`:''}${fxOnHero&&visualMeta.amount?`<span class="impact-number ${visualMeta.kind}">${visualMeta.amount}</span>`:''}</div><div class="battle-center">${uiImg(ASSETS.ui.vs,'VS','display:block;width:min(132px,20vw);height:auto;object-fit:contain;margin:auto;')}</div><div class="fighter enemy ${enemyAct?'is-acting':''} ${heroAct&&!selfFx?'is-hit':''}">${visual(s.art,'','fighter-art')}<div class="name-line">${esc(s.name)}</div><div class="monster-skill"><b>${esc(s.skill)}</b><span>${esc(s.skillText)}</span></div><div class="hp enemy-hp"><i style="width:${ehp}%"></i></div>${stats(enemyState)}${fxOnEnemy&&effect?`<img class="battle-effect ${visualMeta.kind}" src="${effect}" alt="">`:''}${fxOnEnemy&&visualMeta.amount?`<span class="impact-number ${visualMeta.kind}">${visualMeta.amount}</span>`:''}</div>${showChosen&&run.round<3?`<div class="combat-card-rail player-rail">${selectedCardsHtml(pc,activeStep?.who==='player'?activeStep.slot:-1,false)}</div><div class="combat-card-rail enemy-rail">${selectedCardsHtml(ec,activeStep?.who==='enemy'?activeStep.slot:-1,true)}</div>`:''}</section>`}
function cardHint(c){if(c.kind==='stat')return c.stat==='crit'?`爆擊率\n${c.pct}%`:`提升\n${c.pct}%`;return CARD_HINT[c.id]||String(c.text||'').replace(/[＋+,，]/g,'\n')}
function cardHtml(c,i){const used=run.used.includes(i),order=run.selected.indexOf(i)+1,hint=cardHint(c);return `<button class="battle-card ${c.color} ${used?'used':''} ${order?'selected':''}" data-card="${i}" ${used?'disabled':''}><span class="card-order">${order||''}</span>${slot('card-'+c.id)}<b>${esc(c.name)}</b><small>${esc(hint)}</small></button>`}
function ensureSelectionTimer(){if(screen!=='cards'||run.round>=3)return;if(!run.selectDeadline)run.selectDeadline=Date.now()+60000;clearTimeout(selectTimeout);clearInterval(selectTicker);selectTimeout=setTimeout(()=>{if(screen!=='cards')return;autoFillSelection();confirmCards(true)},Math.max(0,run.selectDeadline-Date.now()));selectTicker=setInterval(()=>{const el=document.querySelector('[data-select-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((run.selectDeadline-Date.now())/1000)))},250)}
function renderCards(){queueMicrotask(ensureSelectionTimer);return `<main class="battle-screen">${combatHeader()}<section class="card-zone"><div class="section-title" style="margin-bottom:8px"><b data-select-time style="font-size:28px">${Math.max(0,Math.ceil(((run.selectDeadline||Date.now()+60000)-Date.now())/1000))}</b></div><div class="hand-grid">${run.hand.map(cardHtml).join('')}</div><div style="width:min(190px,48vw);margin:10px auto 0">${imageButton(ASSETS.ui.confirm,'確認出牌',`data-action="confirm-cards" ${run.selected.length!==3?'disabled':''}`)}</div></section></main>`}
function autoFillSelection(){const available=run.hand.map((_,i)=>i).filter(i=>!run.used.includes(i)&&!run.selected.includes(i));while(run.selected.length<3&&available.length)run.selected.push(available.splice(Math.floor(Math.random()*available.length),1)[0])}
function confirmCards(auto=false){if(run.selected.length!==3){if(!auto)return;autoFillSelection()}if(run.selected.length!==3)return;clearTimeout(selectTimeout);clearInterval(selectTicker);run.selectDeadline=0;run.enemySelected=aiPickIndices();startQuiz()}
function startQuiz(){answerFeedback=null;run.correct=0;run.qIndex=0;run.qs=questions();run.quizStarted=performance.now();screen='quiz';render();startQuestionTimer()}
function startQuestionTimer(){clearTimeout(questionTimeout);clearInterval(questionTicker);run.questionDeadline=Date.now()+10000;questionTimeout=setTimeout(()=>answer(null,true),10000)}
function answer(value,timedOut=false){const cur=run.qs[run.qIndex];if(!cur||screen!=='quiz'||answerFeedback)return;clearTimeout(questionTimeout);const ok=!timedOut&&value===cur.answer;if(ok)run.correct++;else run.wrongAnswers.push({word:cur.word,answer:cur.answer,selected:value||'未作答'});answerFeedback={selected:value,correct:cur.answer,ok,timedOut};render();questionTimeout=setTimeout(()=>{answerFeedback=null;run.qIndex++;if(run.qIndex>=3){const elapsed=Math.min(30000,Math.max(1,Math.round(performance.now()-run.quizStarted)-1800));resolveRound(elapsed);return}render();startQuestionTimer()},900)}
function renderQuiz(){const cur=run.qs[run.qIndex],fb=answerFeedback;const option=o=>{let bg='#e2ddd4',border='#c8c0b4',color='#29332f';if(fb){if(o===cur.answer){bg='#c8d9cb';border='#78957e';color='#23462d'}else if(o===fb.selected){bg='#e1c4c1';border='#b87873';color='#702f2b'}else{bg='#e8e4dc';border='#d3ccc1';color='#6f736f'}}return `<button class="answer-btn" data-answer="${esc(o)}" ${fb?'disabled':''} style="background:${bg};border:2px solid ${border};color:${color};">${esc(o)}</button>`};return `<main class="battle-screen combat-focus">${combatHeader({showChosen:true})}<section class="quiz-zone compact-quiz"><h1 style="display:inline-block;background:#d9ded8;border:2px solid #b9c4bc;border-radius:18px;padding:10px 22px;color:#2f3e36;">${esc(cur.word)}</h1><div class="answer-grid">${cur.options.map(option).join('')}</div></section></main>`}
function aiPickIndices(){return shuffle(run.enemyHand.map((_,i)=>i).filter(i=>!run.enemyUsed.includes(i))).slice(0,3)}
function playerCards(){return run.selected.map(i=>run.hand[i])}function enemyCards(){return run.enemySelected.map(i=>run.enemyHand[i])}
function executeCard(actor,target,card,correct,pair,slotIndex,state,speedWin){const bond=bondMultiplier(pair,card);let boost=1;if(state.pendingBoost>1&&card.id!=='boost'){boost=state.pendingBoost;state.pendingBoost=1}const logs=resolveCardAction(actor,target,card,correct,{bond,boost,offensiveIndex:state.offensiveCount,cards:pair,slotIndex,speedWin});if(card.id==='boost')state.pendingBoost=supportBoost(card,actor);if(isOffensive(card))state.offensiveCount++;afterAction(actor,target,logs);return logs}
function flatDamage(target,amount){let dmg=Math.max(0,Math.round(amount));if(target.shield>0){const block=Math.min(target.shield,dmg);target.shield-=block;dmg-=block}target.hp=Math.max(0,target.hp-dmg);return dmg}
function monsterRoundStart(s,E,logs){const lv=run.level||1;if(s.id==='moss'){const v=Math.round(E.maxHp*(lv>=10?.15:.12));E.shield+=v;logs.push(`孢子甲殼：護盾 +${v}`);if(lv>=10&&E.hp<=E.maxHp*.5){const heal=Math.min(E.maxHp-E.hp,Math.round(E.maxHp*.05));E.hp+=heal;if(heal>0)logs.push(`孢子再生 +${heal}`)}}if(s.id==='beetle'){const v=Math.round(E.maxHp*(lv>=10?.18:.15));E.shield+=v;logs.push(`硬殼防禦：護盾 +${v}`)}if(s.id==='shadow'&&!E.enraged&&E.hp<=E.maxHp*(lv>=15?.60:.50)){E.enraged=true;E.atk*=lv>=15?1.32:1.25;E.poison=[];E.armorBreak=[];E.atkDown=[];E.critLock=0;logs.push(`暗影狂暴：攻擊 +${lv>=15?32:25}%，清除負面狀態`)}}
function monsterAfterPlayer(s,P,dealt,logs){if(s.id==='beetle'&&dealt>0&&P.hp>0){const ratio=(run.level||1)>=10?.16:.10,v=Math.min((run.level||1)>=10?70:45,Math.max(8,Math.round(dealt*ratio))),actual=flatDamage(P,v);logs.push(`硬殼反震 ${actual}`)}}
function monsterAfterEnemy(s,P,E,prevPhp,slot,first,logs){const dealt=Math.max(0,prevPhp-P.hp),lv=run.level||1;if(s.id==='rabbit'&&first==='enemy'&&slot===0&&P.hp>0){const extra=Math.max(12,Math.round(E.atk*.32)),actual=flatDamage(P,extra);logs.push(`霧影突襲 ${actual}`)}if(s.id==='rabbit'&&lv>=10&&slot===2&&P.hp>0){const extra=Math.max(10,Math.round(E.atk*.22)),actual=flatDamage(P,extra);logs.push(`殘影追擊 ${actual}`)}if(s.id==='shadow'&&dealt>0&&E.hp>0){const heal=Math.min(E.maxHp-E.hp,Math.round(dealt*(lv>=10?.35:.25)));if(heal>0){E.hp+=heal;logs.push(`暗影汲取 +${heal}`)}}}
function summaryHtml(){const st=run?.stats||freshStats(),rate=st.total?Math.round(st.correct/st.total*100):0;return `<div class="battle-summary"><div><b>${rate}%</b><span>答對率</span></div><div><b>${Math.round(st.damage)}</b><span>輸出傷害</span></div><div><b>${Math.round(st.heal)}</b><span>恢復生命</span></div></div>`}
function wrongAnalysisHtml(){const wrong=run?.wrongAnswers||[];if(!wrong.length)return `<section class="wrong-analysis"><h2>錯題分析</h2><p>本次全對</p></section>`;return `<section class="wrong-analysis"><h2>錯題分析</h2>${wrong.map(x=>`<div class="wrong-item"><b>${esc(x.word)}</b><span>正確：${esc(x.answer)}</span><small>你的答案：${esc(x.selected)}</small></div>`).join('')}</section>`}
function resolveRound(playerMs){clearTimeout(questionTimeout);run.stats.correct+=run.correct;run.stats.total+=3;const s=stage(),pc=playerCards(),ec=enemyCards(),enemyCorrect=pick([1,2,2,3,3]),enemyMs=s.id==='rabbit'?2500+Math.floor(Math.random()*9500):4000+Math.floor(Math.random()*22000),first=playerMs<=enemyMs?'player':'enemy';run.used.push(...run.selected);run.enemyUsed.push(...run.enemySelected);const P=run.player,E=run.enemy,ps={pendingBoost:1,offensiveCount:0},es={pendingBoost:1,offensiveCount:0},sequence=[],roundStartLogs=[];monsterRoundStart(s,E,roundStartLogs);run.actionStartPlayer=cloneFighter(P);run.actionStartEnemy=cloneFighter(E);if(first==='player')sequence.push('player','enemy','player','enemy','player','enemy');else sequence.push('enemy','player','enemy','player','enemy','player');const counts={player:0,enemy:0},steps=[];for(const who of sequence){if(P.hp<=0||E.hp<=0)break;const slot=counts[who]++,beforePhp=P.hp,beforeEPool=E.hp+E.shield,beforePhpForHeal=P.hp;let logs=[];if(who==='player')logs=executeCard(P,E,pc[slot],run.correct,pc,slot,ps,first==='player');else logs=executeCard(E,P,ec[slot],enemyCorrect,ec,slot,es,first==='enemy');if(who==='player'){const dealt=Math.max(0,beforeEPool-(E.hp+E.shield));run.stats.damage+=dealt;run.stats.heal+=Math.max(0,P.hp-beforePhpForHeal);monsterAfterPlayer(s,P,dealt,logs)}else monsterAfterEnemy(s,P,E,beforePhp,slot,first,logs);if(!steps.length&&roundStartLogs.length)logs.unshift(...roundStartLogs);steps.push({who,slot,card:who==='player'?pc[slot]:ec[slot],logs:[...logs],player:cloneFighter(P),enemy:cloneFighter(E)})}if(P.hp>0){const before=P.hp,petLogs=[];applyPetRoundEnd(P,pc,petLogs);run.stats.heal+=Math.max(0,P.hp-before);if(petLogs.length&&steps.length){steps[steps.length-1].logs.push(...petLogs);steps[steps.length-1].player=cloneFighter(P)}}run.steps=steps;run.stepIndex=0;run.enemyCorrect=enemyCorrect;run.log=steps.flatMap(x=>x.logs).slice(-16);screen='action';render();scheduleActionStep()}
function startFinalDuel(){clearTimers();run.round=3;run.selected=[];run.enemySelected=[];const s=stage(),P=run.player,E=run.enemy,steps=[],startLogs=[];monsterRoundStart(s,E,startLogs);run.actionStartPlayer=cloneFighter(P);run.actionStartEnemy=cloneFighter(E);let pSlot=0,eSlot=0;for(let cycle=1;cycle<=5;cycle++){const order=s.id==='rabbit'?['enemy','player']:['player','enemy'];for(const who of order){if(P.hp<=0||E.hp<=0)break;const beforeP=P.hp,beforeEPool=E.hp+E.shield,beforeHeal=P.hp,slot=who==='player'?pSlot++:eSlot++;let logs=[];if(who==='player'){logs=resolveAutoBasic(P,E);afterAction(P,E,logs);const dealt=Math.max(0,beforeEPool-(E.hp+E.shield));run.stats.damage+=dealt;run.stats.heal+=Math.max(0,P.hp-beforeHeal);monsterAfterPlayer(s,P,dealt,logs)}else{logs=resolveAutoBasic(E,P);afterAction(E,P,logs);monsterAfterEnemy(s,P,E,beforeP,slot,s.id==='rabbit'?'enemy':'player',logs)}if(!steps.length&&startLogs.length)logs.unshift(...startLogs);steps.push({who,slot,cycle,finalRound:true,card:null,logs:[...logs],player:cloneFighter(P),enemy:cloneFighter(E)})}if(P.hp<=0||E.hp<=0)break}run.steps=steps;run.stepIndex=0;run.log=steps.flatMap(x=>x.logs).slice(-16);screen='action';render();scheduleActionStep()}
function stepDelay(){const step=run.steps[run.stepIndex];if(step?.finalRound)return 1300;if(step?.card?.id==='sacrifice')return 1900;if(step?.who==='player'&&meta.role==='archer'&&isOffensive(step.card))return Math.max(1250,1550-step.slot*80);return 1550}
function scheduleActionStep(){clearTimeout(actionTimer);actionTimer=setTimeout(()=>{if(screen!=='action')return;if(run.stepIndex<run.steps.length-1){run.stepIndex++;render();scheduleActionStep()}else actionTimer=setTimeout(()=>{if(run.player.hp<=0||run.enemy.hp<=0||run.round>=3)finishBattle();else nextRound()},1100)},stepDelay())}
function lifeDelta(prevP,prevE,p,e){const parts=[],pd=Math.round(p.hp-prevP.hp),ed=Math.round(e.hp-prevE.hp);if(pd)parts.push(`我方生命 ${pd>0?'+':''}${pd}`);if(ed)parts.push(`敵方生命 ${ed>0?'+':''}${ed}`);return parts.length?`<div style="margin-top:5px;color:#a84943;font-size:20px;font-weight:500">${parts.join('　')}</div>`:''}
function renderAction(){const step=run.steps[run.stepIndex],prev=run.stepIndex>0?run.steps[run.stepIndex-1]:null,prevP=prev?.player||run.actionStartPlayer,prevE=prev?.enemy||run.actionStartEnemy,p=step?.player||run.player,e=step?.enemy||run.enemy,metaFx=actionVisual(step,prevP,prevE,p,e),title=step?.finalRound?`第 ${step.cycle} 輪 · 普通攻擊`:(step?.card?cardSummary(step.card):'普通攻擊'),actorColor=step?.who==='player'?'#447257':'#49739b';return `<main class="battle-screen combat-focus action-screen">${combatHeader({playerState:p,enemyState:e,activeStep:step,showChosen:run.round<3,visualMeta:metaFx})}<section class="action-status"><h1>${esc(title)}</h1><div class="battle-log current-log">${(step?.logs||[]).slice(-3).map(x=>`<p style="color:${actorColor}">${esc(x)}</p>`).join('')}${lifeDelta(prevP,prevE,p,e)}</div></section></main>`}
function nextRound(){if(run.player.hp<=0||run.enemy.hp<=0||run.round>=3)return finishBattle();if(run.round===1){run.round=2;run.selected=[];run.enemySelected=[];run.selectDeadline=0;screen='cards';render();return}if(run.round===2){startFinalDuel();return}}
function rewardStage(){if(run.stageRewarded)return run.lastReward;run.stageRewarded=true;run.lastReward=addXp(80+run.stageIndex*25);return run.lastReward}
function finishBattle(){const p=run.player.hp/run.player.maxHp,e=run.enemy.hp/run.enemy.maxHp,win=run.enemy.hp<=0||(run.player.hp>0&&p>=e);if(!win){screen='lose';render();return}rewardStage();if(run.stageIndex>=STAGES.length-1){screen='win';render();return}screen='stage-clear';render()}
function nextStage(){run.player.hp=Math.min(run.player.maxHp,run.player.hp+Math.round(run.player.maxHp*.2));run.player.poison=[];run.player.armorBreak=[];run.player.atkDown=[];run.player.defBoost=[];run.player.critLock=0;run.stageIndex++;beginStage()}
function rewardHtml(){const r=run?.lastReward;if(!r)return '';return `<div class="growth-reward"><b>EXP +${r.amount}</b><span>Lv.${meta.level} · ${esc(titleFor(meta.level))}</span>${r.levels.length?`<strong>LEVEL UP</strong>`:''}</div>`}
function renderStageClear(){return `<main class="result-screen"><section class="result-card stage-clear-card"><h1>勝利</h1>${rewardHtml()}<div class="stage-fight-btn">${imageButton(ASSETS.ui.fight,'下一戰','data-action="next-stage"')}</div></section></main>`}
function renderResult(win){return `<main class="result-screen"><section class="result-card final-result-card"><h1>${win?'完成冒險':'挑戰失敗'}</h1>${summaryHtml()}${win?rewardHtml():''}${wrongAnalysisHtml()}<button class="primary-btn" data-action="retry">重新開始</button><button class="secondary-btn" data-action="home">回首頁</button></section></main>`}
function render(){app.innerHTML=screen==='home'?renderHome():screen==='setup'?renderSetup():screen==='cards'?renderCards():screen==='quiz'?renderQuiz():screen==='action'?renderAction():screen==='stage-clear'?renderStageClear():screen==='win'?renderResult(true):screen==='lose'?renderResult(false):renderHome();bind()}
function bind(){document.querySelector('[data-action="setup"]')?.addEventListener('click',openSetup);document.querySelector('[data-action="start"]')?.addEventListener('click',startRun);document.querySelector('[data-action="pk"]')?.addEventListener('click',startPk);document.querySelector('[data-action="quit"]')?.addEventListener('click',()=>{clearTimers();screen='setup';render()});document.querySelector('[data-action="confirm-cards"]')?.addEventListener('click',()=>confirmCards(false));document.querySelector('[data-action="next-stage"]')?.addEventListener('click',nextStage);document.querySelector('[data-action="retry"]')?.addEventListener('click',startRun);document.querySelector('[data-action="home"]')?.addEventListener('click',()=>{clearTimers();screen='home';render()});document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{meta.role=b.dataset.role;saveMeta();render()}));document.querySelectorAll('[data-pet]').forEach(b=>b.addEventListener('click',()=>{meta.pet=b.dataset.pet;saveMeta();render()}));document.querySelectorAll('[data-card]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.card);if(run.used.includes(i))return;const at=run.selected.indexOf(i);if(at>=0)run.selected.splice(at,1);else if(run.selected.length<3)run.selected.push(i);render()}));document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.answer,false)))}
render();
