import {ASSETS,preloadRoleAction} from './assets.js';
import {cardSummary,isOffensive} from './cards.js';
import {playBattleStep,cancelBattleFx} from './battle-fx.js';
import {setMusic} from './audio.js';
import {seasonOrdinal,seasonTier} from './progression-v2.js';

const CARD_HINT={combo:'3次連擊\n每擊 50%',desperate:'重擊 200%\n自身降防',poison:'傷害\n中毒 3回合',break:'傷害\n降防 2回合',sun:'傷害\n封鎖爆擊 2回合',preempt:'傷害\n降攻 2回合',regen:'立即回血\n持續回血',sacrifice:'超高傷害\n消耗生命',restore:'大量回血\n溢出護盾',diamond:'防禦提升\n持續 2回合',aegis:'獲得護盾\n戰鬥期間有效',boost:'強化下張牌\n立即護盾'};

export function createPkMode({app,meta,ROLES,PETS,visual,effects,onExit,onSeasonResult=()=>{},onQuizResult=()=>{},onWordResults=()=>{}}){
  let socket=null,alive=false,status='idle',round=1,hand=[],used=[],selected=[],qs=[],qIndex=0,answers=[],started=0,me=null,opponent=null,last=null,stepIndex=0,stepTimer=null,actionToken=0,queueTicker=null,queueTakeoverTimer=null,queueStartedAt=0,selectDeadline=0,selectTimeout=null,selectTicker=null,questionDeadline=0,questionTimeout=null,answerFeedback=null,spokenQuestionKey='',seasonReported=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function speakEnglishOnce(word,key){if(!word||!key||spokenQuestionKey===key||!('speechSynthesis' in window)||typeof SpeechSynthesisUtterance==='undefined')return;spokenQuestionKey=key;try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(word));u.lang='en-US';u.rate=.9;u.pitch=1;u.volume=1;window.speechSynthesis.speak(u)}catch{}}
  const wsUrl=()=>`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/match`;
  function send(v){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(v))}
  function clearLocalTimers(){clearInterval(queueTicker);clearInterval(queueTakeoverTimer);queueTicker=queueTakeoverTimer=null;clearTimeout(stepTimer);clearTimeout(selectTimeout);clearInterval(selectTicker);clearTimeout(questionTimeout);stepTimer=selectTimeout=questionTimeout=null;selectTicker=null}
  function stop(exit=true){alive=false;actionToken++;cancelBattleFx();clearLocalTimers();if(socket){try{socket.close(1000,'leave')}catch{}socket=null}if(exit)onExit()}
  async function start(){stop(false);answerFeedback=null;seasonReported=false;alive=true;status='queue';setMusic('menu');queueStartedAt=Date.now();renderQueue();try{await fetch('/api/question-identity',{credentials:'same-origin',cache:'no-store'})}catch{}if(!alive)return;socket=new WebSocket(wsUrl());socket.onopen=()=>send({type:'join',profile:{name:meta.playerName,role:meta.role,pet:meta.pet,level:Math.max(1,Math.min(80,Math.round(Number(meta.level)||1))),rpg:meta.rpg}});socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handle(m)};socket.onerror=()=>{if(alive&&status==='queue')renderQueue('連線失敗')};socket.onclose=()=>{if(alive&&status==='queue')renderQueue('連線中斷')}}
  function makeQuestions(items){return Array.isArray(items)?items.filter(x=>x&&typeof x.word==='string'&&Array.isArray(x.options)&&x.options.length===4):[]}
  function reportSeason(m){if(seasonReported||!m?.finished)return;seasonReported=true;onSeasonResult(m.winner==='self'?'win':m.winner==='opponent'?'loss':'draw',m.season||null,m.correct||0)}
  function handle(m){if(m.type==='quiz-reviewed'){onWordResults(m.wordResults);return}if(m.type==='queued'){queueStartedAt=Date.now();status='queue';renderQueue();return}if(m.type==='matched'){clearInterval(queueTicker);clearInterval(queueTakeoverTimer);queueTicker=queueTakeoverTimer=null;status='cards';round=1;hand=m.hand||[];used=[];selected=[];selectDeadline=0;me=m.self;opponent=m.opponent;void preloadRoleAction(opponent?.profile?.role);qs=[];answers=[];render();return}if(m.type==='quiz-started'){qs=makeQuestions(m.questions||[]);if(qs.length!==5){renderQueue('題目同步失敗');return}answerFeedback=null;qIndex=0;answers=[];started=performance.now();status='quiz';render();startQuestionTimer();return}if(m.type==='waiting-opponent'){status='wait';render();return}if(m.type==='battle-result'){const beforeMe=me,beforeOpponent=opponent;me=m.self;opponent=m.opponent;last={...m,beforeMe,beforeOpponent};round=m.round;stepIndex=0;onQuizResult(Number(m.correct)||0);reportSeason(m);status=(m.steps||[]).length?'action':m.finished?'finished':'wait';render();if(status==='action')scheduleStep();return}if(m.type==='opponent-left'){status='finished';last={winner:'self',note:'對手離線',logs:[]};render();return}if(m.type==='error'){status='error';clearLocalTimers();app.innerHTML=`<main class="pk-screen"><section class="pk-card pk-queue-card"><h1>對戰暫時中斷</h1><p>${esc(m.message||'請重新配對')}</p><button class="secondary-btn pk-cancel-btn" data-pk-cancel>返回</button></section></main>`;app.querySelector('[data-pk-cancel]')?.addEventListener('click',()=>stop(true))}}
  function uiImg(src,label,style=''){return `<img src="${esc(src)}" alt="${esc(label)}" style="${style}" decoding="async">`}
  function imageButton(src,label,attrs=''){return `<button ${attrs} aria-label="${esc(label)}" style="border:0;background:transparent;padding:0;display:grid;place-items:center;width:100%;cursor:pointer">${uiImg(src,label,'display:block;max-width:100%;height:auto;object-fit:contain;')}</button>`}
  function cardArt(c,mini=false){if(c?.exclusive){const r=ROLES[c.role]||ROLES.warrior,src=c.role&&c.level?`/images/skill-${c.role}-${c.level}.png`:r.art;return `<span class="exclusive-card-art ${mini?'mini':''}">${uiImg(src,c.name,'')}</span>`}return `<span class="asset-slot" data-asset="card-${esc(c.id)}"></span>`}
  function cardHint(c){if(c.kind==='stat')return c.stat==='crit'?`爆擊率\n${c.pct}%`:`提升\n${c.pct}%`;return CARD_HINT[c.id]||String(c.text||'').replace(/[＋+,，]/g,'\n')}
  function card(c,i){const unavailable=used.includes(i),order=selected.indexOf(i)+1,hint=cardHint(c);return `<button class="battle-card ${c.color} ${c.exclusive?'exclusive-card':''} ${unavailable?'used':''} ${order?'selected':''}" data-pk-card="${i}" ${unavailable?'disabled':''}><span class="card-order">${order?'•'.repeat(order):''}</span>${cardArt(c,false)}<b>${esc(c.name)}</b><small>${esc(hint)}</small></button>`}
  function statItem(src,value,label){return `<span class="battle-stat-line">${uiImg(src,label,'')}<b>${esc(value)}</b></span>`}
  function shieldStat(value){return `<span class="battle-stat-line shield-stat">${uiImg(ASSETS.ui.shield,'護盾','')}<b>${esc(Math.max(0,Math.round(value||0)))}</b></span>`}
  function fighter(f,profile,enemy=false,cls='',fx=null){profile=profile||{};const r=ROLES[profile.role]||ROLES.warrior,pct=Math.max(0,Math.min(100,f.hp/f.maxHp*100));return `<div class="fighter ${enemy?'enemy':'hero'} ${cls}">${visual(r.art,'','fighter-art')}<div class="name-line">${esc(profile.name||r.name)}${profile.level?` · Lv.${profile.level}`:''}</div><div class="hp ${enemy?'enemy-hp':''}"><i style="width:${pct}%"></i></div><div class="stat-row">${statItem(ASSETS.ui.hp,`${Math.round(f.hp)}/${Math.round(f.maxHp)}`,'生命')}${statItem(ASSETS.ui.atk,Math.round(f.atk),'攻擊')}${statItem(ASSETS.ui.def,Math.round(f.def),'防禦')}${statItem(ASSETS.ui.crit,`${Math.round(f.crit*100)}%`,'爆擊率')}${shieldStat(f.shield)}</div>${fx?.show&&effects?.[fx.kind]?`<img class="battle-effect ${fx.kind}" src="${effects[fx.kind]}" alt="">`:''}${fx?.show&&fx.amount?`<span class="impact-number ${fx.kind}">${fx.amount}</span>`:''}</div>`}
  function selectedHtml(cards=[],active=-1,enemy=false){return `<div class="selected-action-cards ${enemy?'enemy-cards':''}">${cards.map((c,i)=>`<div class="mini-card ${c.color} ${c.exclusive?'exclusive-card':''} ${i===active?'active':''}">${cardArt(c,true)}<b><span class="card-name-full">${esc(c.name)}</span><span class="card-name-short">${esc(String(c.name||'').slice(0,2))}</span></b><span>${'•'.repeat(i+1)}</span></div>`).join('')}</div>`}
  function myCards(){return round<=2?selected.map(i=>hand[i]).filter(Boolean):[]}
  function actionVisual(step,prevSelf,prevOpp,self,opp){if(!step)return null;const mine=step.who==='self',actorPrev=mine?prevSelf:prevOpp,actorNow=mine?self:opp,targetPrev=mine?prevOpp:prevSelf,targetNow=mine?opp:self,logs=step.logs||[],card=step.card;const damage=Math.max(0,Math.round(((targetPrev?.hp||0)+(targetPrev?.shield||0))-((targetNow?.hp||0)+(targetNow?.shield||0)))),heal=Math.max(0,Math.round((actorNow?.hp||0)-(actorPrev?.hp||0))),shield=Math.max(0,Math.round((actorNow?.shield||0)-(actorPrev?.shield||0))),crit=logs.some(x=>String(x).includes('爆擊'));let kind='slash',selfFx=false;if(heal>0||card?.id==='restore'||card?.id==='regen'||card?.stat==='hp'){kind='heal';selfFx=true}else if(shield>0||card?.id==='diamond'||card?.id==='aegis'||card?.stat==='def'){kind='guard';selfFx=true}else if(crit||card?.id==='sacrifice')kind='crit';else if(card&&!isOffensive(card)){kind='guard';selfFx=true}return {kind,selfFx,mine,crit,amount:heal?`+${heal}`:shield?`+${shield}`:damage?`-${damage}`:''}}
  function header({self=me,opp=opponent,step=null,showCards=false,fx=null}={}){const my=myCards(),their=last?.opponentCards||[],mine=step?.who==='self',selfClass=step?(mine?'is-acting':fx?.selfFx?'':'is-hit'):'',oppClass=step?(!mine?'is-acting':fx?.selfFx?'':'is-hit'):'',fxSelf=false,fxOpp=false,stagePadding=showCards&&round<=2?'':'padding-bottom:30px;';return `<header class="battle-top"><button data-pk-quit aria-label="返回" style="border:0;background:transparent;padding:0;justify-self:start;width:132px">${uiImg(ASSETS.ui.back,'返回','display:block;width:100%;height:auto;object-fit:contain;')}</button><b>線上對戰</b><span>${status==='wait'?'等待對手':''}</span></header><section class="combat-stage focus-stage " style="${stagePadding}">${fighter(self,self?.profile||me?.profile,false,selfClass,{...fx,show:fxSelf})}<div class="battle-center">${uiImg(ASSETS.ui.vs,'VS','display:block;width:min(132px,20vw);height:auto;object-fit:contain;margin:auto;')}</div>${fighter(opp,opp?.profile||opponent?.profile,true,oppClass,{...fx,show:fxOpp})}${showCards&&round<=2?`<div class="combat-card-rail player-rail">${selectedHtml(my,mine?step?.slot:-1,false)}</div><div class="combat-card-rail enemy-rail">${selectedHtml(their,!mine?step?.slot:-1,true)}</div>`:''}</section>`}
  function renderQueue(message='等待玩家挑戰'){const remaining=Math.max(0,Math.ceil((queueStartedAt+60000-Date.now())/1000));app.innerHTML=`<main class="pk-screen"><section class="pk-card pk-queue-card"><h1>配對中</h1><p>${esc(message)}</p><p class="pk-ai-countdown" data-pk-ai-countdown>等待 ${remaining} 秒後，將由 AI 挑戰者接手</p><div class="pk-wait" aria-label="配對中"></div><button class="secondary-btn pk-cancel-btn" data-pk-cancel>取消</button></section></main>`;app.querySelector('[data-pk-cancel]')?.addEventListener('click',()=>stop(true));clearInterval(queueTicker);if(status==='queue')queueTicker=setInterval(()=>{const el=app.querySelector('[data-pk-ai-countdown]');if(el)el.textContent=`等待 ${Math.max(0,Math.ceil((queueStartedAt+60000-Date.now())/1000))} 秒後，將由 AI 挑戰者接手`},250);clearInterval(queueTakeoverTimer);if(status==='queue')queueTakeoverTimer=setInterval(()=>{if(Date.now()-queueStartedAt>=60000&&status==='queue')send({type:'request-ai'})},2000)}
  function ensureSelectionTimer(){if(status!=='cards'||round>2)return;if(!selectDeadline)selectDeadline=Date.now()+60000;clearTimeout(selectTimeout);clearInterval(selectTicker);selectTimeout=setTimeout(()=>{if(status!=='cards')return;autoFill();beginQuiz(true)},Math.max(0,selectDeadline-Date.now()));selectTicker=setInterval(()=>{const el=app.querySelector('[data-pk-select-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((selectDeadline-Date.now())/1000)))},250)}
  function renderCards(){app.innerHTML=`<main class="pk-battle">${header()}<section class="card-zone"><div class="section-title" style="margin-bottom:8px"><b data-pk-select-time style="font-size:28px">${Math.max(0,Math.ceil(((selectDeadline||Date.now()+60000)-Date.now())/1000))}</b></div><div class="hand-grid">${hand.map((c,i)=>used.includes(i)?'':card(c,i)).join('')}</div><div style="width:min(190px,48vw);margin:10px auto 0">${imageButton(ASSETS.ui.confirm,'確認出牌',`data-pk-confirm ${selected.length!==3?'disabled':''}`)}</div></section></main>`;queueMicrotask(ensureSelectionTimer)}
  function autoFill(){const available=hand.map((_,i)=>i).filter(i=>!used.includes(i)&&!selected.includes(i));while(selected.length<3&&available.length)selected.push(available.splice(Math.floor(Math.random()*available.length),1)[0])}
  function beginQuiz(auto=false){if(selected.length!==3){if(!auto)return;autoFill()}if(selected.length!==3)return;clearTimeout(selectTimeout);clearInterval(selectTicker);selectDeadline=0;answerFeedback=null;qIndex=0;answers=[];qs=[];status='quiz-loading';send({type:'quiz-start',selected:[...selected]});render()}
  function startQuestionTimer(){clearTimeout(questionTimeout);const cur=qs?.[qIndex];speakEnglishOnce(cur?.word,`pk:${started}:${qIndex}:${cur?.word||''}`);questionDeadline=Date.now()+10000;questionTimeout=setTimeout(()=>answer(null,true),10000)}
  function renderQuiz(){const x=qs[qIndex],fb=answerFeedback;const option=o=>{let bg='#e2ddd4',border='#c8c0b4',color='#29332f';if(fb){if(o===fb.selected){bg='#d7e4ed';border='#829bb3';color='#27445b'}else{bg='#e8e4dc';border='#d3ccc1';color='#6f736f'}}return `<button class="answer-btn" data-pk-answer="${esc(o)}" ${fb?'disabled':''} style="background:${bg};border:2px solid ${border};color:${color};">${esc(o)}</button>`};app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="quiz-zone compact-quiz"><h1 style="display:inline-block;background:#d9ded8;border:2px solid #b9c4bc;border-radius:18px;padding:10px 22px;color:#2f3e36;">${esc(x.word)}</h1><div class="answer-grid">${x.options.map(option).join('')}</div></section></main>`}
  function answer(v,timedOut=false){const x=qs[qIndex];if(status!=='quiz'||!x||answerFeedback)return;clearTimeout(questionTimeout);const chosen=timedOut?null:v;answers.push(chosen);answerFeedback={selected:chosen,timedOut};render();questionTimeout=setTimeout(()=>{answerFeedback=null;qIndex++;if(qIndex>=5){if(round<=2)used.push(...selected);send({type:'ready',answers:[...answers]});status='wait';render();return}render();startQuestionTimer()},900)}
  function renderQuizLoading(){app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="resolve-zone"><h1>準備題目</h1><div class="pk-wait"></div><p class="waiting-text">伺服器正在啟動本回合計時</p></section></main>`}
  function renderWait(){app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="resolve-zone"><h1>等待對手</h1><div class="pk-wait"></div><p class="waiting-text">已送出本回合答案</p></section></main>`}
  function lifeDelta(prevSelf,prevOpp,self,opp){const parts=[],sd=Math.round(self.hp-prevSelf.hp),od=Math.round(opp.hp-prevOpp.hp);if(sd)parts.push(`我方生命 ${sd>0?'+':''}${sd}`);if(od)parts.push(`對手生命 ${od>0?'+':''}${od}`);return parts.length?`<div style="margin-top:5px;color:#a84943;font-size:20px;font-weight:500">${parts.join('　')}</div>`:''}
  function renderAction(){const step=last?.steps?.[stepIndex],prev=stepIndex>0?last.steps[stepIndex-1]:null,prevSelf=prev?.self||last?.beforeMe,prevOpp=prev?.opponent||last?.beforeOpponent,self=step?.self||me,opp=step?.opponent||opponent,fx=actionVisual(step,prevSelf,prevOpp,self,opp);if(step?.autoDuel){app.innerHTML=`<main class="pk-battle combat-focus action-screen auto-duel-screen">${header({self,opp,step,showCards:false,fx})}<section class="action-status pk-auto-status"><h1>第 ${esc(step.cycle||3)} 回合 · 普通攻擊</h1><div class="battle-log current-log">${(step?.logs||[]).slice(-4).map(x=>`<p>${esc(x)}</p>`).join('')}${lifeDelta(prevSelf,prevOpp,self,opp)}</div></section></main>`;return}const title=step?.card?cardSummary(step.card):'',actorColor=step?.who==='self'?'#447257':'#49739b';app.innerHTML=`<main class="pk-battle combat-focus action-screen">${header({self,opp,step,showCards:true,fx})}<section class="action-status"><h1>${esc(title)}</h1><div class="battle-log current-log">${(step?.logs||[]).slice(-3).map(x=>`<p style="color:${actorColor}">${esc(x)}</p>`).join('')}${lifeDelta(prevSelf,prevOpp,self,opp)}</div></section></main>`}
  function stepDelay(){const step=last?.steps?.[stepIndex];if(step?.who==='self')return 2000;if(step?.autoDuel)return 720;if(step?.card?.id==='sacrifice')return 1900;return 1550}
  async function scheduleStep(){const token=++actionToken;clearTimeout(stepTimer);if(!alive||status!=='action')return;const step=last?.steps?.[stepIndex],prev=stepIndex>0?last.steps[stepIndex-1]:null,previous={player:prev?.self||last?.beforeMe,enemy:prev?.opponent||last?.beforeOpponent};if(step)await playBattleStep({step:{...step,who:step.who==='self'?'player':'enemy',player:step.self,enemy:step.opponent},previous,role:me?.profile?.role||meta.role,duration:step.autoDuel?800:1150});if(token!==actionToken||!alive||status!=='action')return;stepTimer=setTimeout(()=>{if(token!==actionToken||!alive||status!=='action')return;if(stepIndex<(last?.steps?.length||0)-1){stepIndex++;render();scheduleStep()}else stepTimer=setTimeout(()=>{if(!alive||status!=='action')return;if(last?.finished){status='finished';render()}else next()},500)},step?.autoDuel?65:100)}
  function renderEnd(){const win=last?.winner==='self',draw=last?.winner==='draw',note=last?.note||'',victory=win&&!note?uiImg(ASSETS.ui.victor,'勝利','display:block;width:min(260px,72vw);max-height:120px;object-fit:contain;margin:0 auto 14px;'):'',fail=!win&&!draw&&!note?uiImg(ASSETS.ui.fail,'失敗','display:block;width:min(260px,72vw);max-height:120px;object-fit:contain;margin:0 auto 14px;'):'',title=note||(draw?'平手':''),season=last?.season,seasonHtml=season?`<div class="season-badge">${esc(seasonOrdinal(season.season))} ${esc(seasonTier(season.points).name)}</div>`:'';app.innerHTML=`<main class="result-screen"><section class="result-card">${victory}${fail}${title?`<h1>${esc(title)}</h1>`:''}${seasonHtml}<button class="primary-btn" data-pk-again>再次配對</button><button class="secondary-btn" data-pk-home>回上一頁</button></section></main>`;app.querySelector('[data-pk-again]')?.addEventListener('click',start);app.querySelector('[data-pk-home]')?.addEventListener('click',()=>stop(true))}
  function next(){if(round>=2||last?.finished){status='finished';render();return}round++;selected=[];selectDeadline=0;qs=[];answers=[];status='cards';render()}
  function render(){if(!alive)return;setMusic(status==='quiz'||status==='wait'||status==='quiz-loading'?'none':status==='action'?'fight':'menu');if(status==='queue')return renderQueue();if(status==='cards')renderCards();else if(status==='quiz-loading')renderQuizLoading();else if(status==='quiz')renderQuiz();else if(status==='wait')renderWait();else if(status==='action')renderAction();else if(status==='finished')renderEnd();bind()}
  function bind(){app.querySelector('[data-pk-quit]')?.addEventListener('click',()=>stop(true));app.querySelectorAll('[data-pk-card]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.pkCard);if(used.includes(i))return;const at=selected.indexOf(i);if(at>=0)selected.splice(at,1);else if(selected.length<3)selected.push(i);render()}));app.querySelector('[data-pk-confirm]')?.addEventListener('click',()=>beginQuiz(false));app.querySelectorAll('[data-pk-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.pkAnswer,false)))}
  return {start,stop};
}
