import {cardSummary} from './cards.js';

export function createPkMode({app,meta,ROLES,PETS,WORDS,visual,onExit}){
  let socket=null,alive=false,status='idle',round=1,hand=[],used=[],selected=[],qs=[],qIndex=0,correct=0,started=0,me=null,opponent=null,last=null,stepIndex=0,stepTimer=null,selectDeadline=0,selectTimeout=null,selectTicker=null,questionDeadline=0,questionTimeout=null,questionTicker=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c};
  const wsUrl=()=>`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/match`;
  function send(v){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(v))}
  function clearLocalTimers(){clearTimeout(stepTimer);clearTimeout(selectTimeout);clearInterval(selectTicker);clearTimeout(questionTimeout);clearInterval(questionTicker);stepTimer=selectTimeout=questionTimeout=null;selectTicker=questionTicker=null}
  function stop(exit=true){alive=false;clearLocalTimers();if(socket){try{socket.close(1000,'leave')}catch{}socket=null}if(exit)onExit()}
  function start(){stop(false);alive=true;status='queue';renderQueue('連線中');socket=new WebSocket(wsUrl());socket.onopen=()=>send({type:'join',profile:{name:meta.playerName,role:meta.role,pet:meta.pet}});socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handle(m)};socket.onerror=()=>renderQueue('連線失敗');socket.onclose=()=>{if(alive&&status!=='finished')renderQueue('連線中斷')}}
  function makeQuestions(indices){return indices.map(i=>{const w=WORDS[i%WORDS.length];return {word:w[0],answer:w[1],options:shuffle([...w[2]])}})}
  function handle(m){
    if(m.type==='queued'){status='queue';renderQueue('等待玩家挑戰');return}
    if(m.type==='matched'){status='cards';round=1;hand=m.hand||[];used=[];selected=[];selectDeadline=0;me=m.self;opponent=m.opponent;qs=makeQuestions(m.questions||[0,1,2]);render();return}
    if(m.type==='waiting-opponent'){status='wait';render();return}
    if(m.type==='battle-result'){me=m.self;opponent=m.opponent;last=m;round=m.round;if(m.nextQuestions)qs=makeQuestions(m.nextQuestions);stepIndex=0;status=(m.steps||[]).length?'action':'resolve';render();if(status==='action')scheduleStep();return}
    if(m.type==='opponent-left'){status='finished';last={winner:'self',note:'對手離線',logs:[]};render();return}
    if(m.type==='error'){renderQueue(m.message||'配對失敗')}
  }
  function card(c,i){const unavailable=used.includes(i),order=selected.indexOf(i)+1;return `<button class="battle-card ${c.color} ${unavailable?'used':''} ${order?'selected':''}" data-pk-card="${i}" ${unavailable?'disabled':''}><span class="card-order">${order||''}</span><span class="asset-slot" data-asset="card-${esc(c.id)}"></span><b>${esc(c.name)}</b><small>${c.kind==='stat'?`增加 ${c.pct}%`:c.id==='boost'?`下一張卡 +${c.boost}%`:esc(c.text)}</small></button>`}
  function fighter(f,profile,enemy=false){const r=ROLES[profile.role]||ROLES.warrior,pct=Math.max(0,Math.min(100,f.hp/f.maxHp*100));return `<div class="fighter ${enemy?'enemy':'hero'}">${visual(r.art,'','fighter-art')}<div class="name-line">${esc(profile.name||r.name)}</div><div class="hp ${enemy?'enemy-hp':''}"><i style="width:${pct}%"></i></div><div class="stat-row"><span>生命 ${Math.round(f.hp)}/${Math.round(f.maxHp)}</span><span>攻擊 ${Math.round(f.atk)}</span><span>防禦 ${Math.round(f.def)}</span><span>爆擊 ${Math.round(f.crit*100)}%</span>${f.shield>0?`<span>護盾 ${Math.round(f.shield)}</span>`:''}</div></div>`}
  function selectedHtml(cards=[],active=-1,enemy=false){return `<div class="selected-action-cards ${enemy?'enemy-cards':''}">${cards.map((c,i)=>`<div class="mini-card ${c.color} ${i===active?'active':''}"><span class="asset-slot" data-asset="card-${esc(c.id)}"></span><b>${esc(c.name)}</b><span>${i+1}</span></div>`).join('')}</div>`}
  function myCards(){return round<3?selected.map(i=>hand[i]).filter(Boolean):[]}
  function header({self=me,opp=opponent,step=null,showCards=false}={}){const my=myCards(),their=(last?.opponentCards||[]);return `<header class="battle-top"><button class="text-btn" data-pk-quit>返回</button><b>線上對戰 · 第 ${round} 回合</b><span>${status==='wait'?'等待對手':''}</span></header><section class="combat-stage focus-stage">${fighter(self,self.profile,false)}<div class="battle-center"><strong>${step?esc(step.who==='self'?'我方行動':'對手行動'):'VS'}</strong><small>${round<3?'一張卡＝一次出手':'最終回合'}</small></div>${fighter(opp,opp.profile,true)}${showCards?`<div class="combat-card-rail player-rail">${selectedHtml(my,step?.who==='self'?step.slot:-1,false)}</div><div class="combat-card-rail enemy-rail">${selectedHtml(their,step?.who==='opponent'?step.slot:-1,true)}</div>`:''}</section>`}
  function renderQueue(text){app.innerHTML=`<main class="pk-screen"><section class="pk-card"><h1>${esc(text)}</h1><div class="pk-wait"></div><p class="waiting-text">其他玩家進入後會自動開始</p><button class="secondary-btn" data-pk-cancel>取消</button></section></main>`;app.querySelector('[data-pk-cancel]')?.addEventListener('click',()=>stop(true))}
  function ensureSelectionTimer(){if(status!=='cards'||round>=3)return;if(!selectDeadline)selectDeadline=Date.now()+60000;clearTimeout(selectTimeout);clearInterval(selectTicker);selectTimeout=setTimeout(()=>{if(status!=='cards')return;autoFill();beginQuiz(true)},Math.max(0,selectDeadline-Date.now()));selectTicker=setInterval(()=>{const el=app.querySelector('[data-pk-select-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((selectDeadline-Date.now())/1000)))},250)}
  function renderCards(){app.innerHTML=`<main class="pk-battle">${header()}<section class="card-zone"><div class="section-title"><h1>依順序選 3 張</h1><p>剩餘 <b data-pk-select-time>${Math.max(0,Math.ceil(((selectDeadline||Date.now()+60000)-Date.now())/1000))}</b> 秒　未完成會自動隨機補滿</p></div><div class="hand-grid">${hand.map(card).join('')}</div><button class="primary-btn confirm-cards" data-pk-confirm ${selected.length!==3?'disabled':''}>確認出牌</button></section></main>`;queueMicrotask(ensureSelectionTimer)}
  function autoFill(){const available=hand.map((_,i)=>i).filter(i=>!used.includes(i)&&!selected.includes(i));while(selected.length<3&&available.length)selected.push(available.splice(Math.floor(Math.random()*available.length),1)[0])}
  function beginQuiz(auto=false){if(selected.length!==3){if(!auto)return;autoFill()}if(selected.length!==3)return;clearTimeout(selectTimeout);clearInterval(selectTicker);selectDeadline=0;correct=0;qIndex=0;started=performance.now();status='quiz';render();startQuestionTimer()}
  function startQuestionTimer(){clearTimeout(questionTimeout);clearInterval(questionTicker);questionDeadline=Date.now()+10000;questionTimeout=setTimeout(()=>answer(null,true),10000);questionTicker=setInterval(()=>{const el=app.querySelector('[data-pk-question-time]');if(el)el.textContent=String(Math.max(0,Math.ceil((questionDeadline-Date.now())/1000)))},200)}
  function renderQuiz(){const x=qs[qIndex];app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="quiz-zone compact-quiz"><div class="quiz-progress">${qIndex+1} / 3　剩餘 <b data-pk-question-time>${Math.max(0,Math.ceil(((questionDeadline||Date.now()+10000)-Date.now())/1000))}</b> 秒</div><h1>${esc(x.word)}</h1><div class="answer-grid">${x.options.map(o=>`<button class="answer-btn" data-pk-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div></section></main>`}
  function answer(v,timedOut=false){const x=qs[qIndex];if(status!=='quiz'||!x)return;clearTimeout(questionTimeout);clearInterval(questionTicker);if(!timedOut&&v===x.answer)correct++;qIndex++;if(qIndex>=3){const elapsed=Math.min(30000,Math.max(1,Math.round(performance.now()-started)));if(round<3)used.push(...selected);send({type:'ready',selected:round<3?selected:[],correct,elapsedMs:elapsed});status='wait';render();return}render();startQuestionTimer()}
  function renderWait(){app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="resolve-zone"><h1>等待對手</h1><div class="pk-wait"></div><p class="waiting-text">已送出本回合選擇</p></section></main>`}
  function renderAction(){const step=last?.steps?.[stepIndex],self=step?.self||me,opp=step?.opponent||opponent;app.innerHTML=`<main class="pk-battle combat-focus action-screen">${header({self,opp,step,showCards:true})}<section class="action-status"><h1>${step?.card?esc(cardSummary(step.card)):'基本攻擊'}</h1><div class="battle-log current-log">${(step?.logs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div></section></main>`}
  function scheduleStep(){clearTimeout(stepTimer);stepTimer=setTimeout(()=>{if(!alive||status!=='action')return;if(stepIndex<(last?.steps?.length||0)-1){stepIndex++;render();scheduleStep()}else stepTimer=setTimeout(()=>{status=last?.finished?'finished':'resolve';render()},650)},900)}
  function renderResolve(){const quality=last.correct===3?'150%':last.correct===2?'100%':last.correct===1?'50%':'0%';app.innerHTML=`<main class="pk-battle combat-focus">${header({showCards:true})}<section class="resolve-zone"><h1>${esc(last.orderText||'回合結算')}</h1><div class="result-power">答對 ${last.correct}/3 · 效果 ${quality}</div><div class="battle-log">${(last.logs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div><button class="primary-btn" data-pk-next>${round>=3?'查看結果':'下一回合'}</button></section></main>`}
  function renderEnd(){const win=last?.winner==='self',draw=last?.winner==='draw';app.innerHTML=`<main class="result-screen"><section class="result-card"><h1>${last?.note||(draw?'平手':win?'對戰勝利':'對戰落敗')}</h1><button class="primary-btn" data-pk-again>再次配對</button><button class="secondary-btn" data-pk-home>回上一頁</button></section></main>`;app.querySelector('[data-pk-again]')?.addEventListener('click',start);app.querySelector('[data-pk-home]')?.addEventListener('click',()=>stop(true))}
  function next(){if(round>=3||last?.finished){status='finished';render();return}round++;selected=[];selectDeadline=0;status=round===3?'quiz':'cards';if(status==='quiz'){correct=0;qIndex=0;started=performance.now()}render();if(status==='quiz')startQuestionTimer()}
  function render(){if(!alive)return;if(status==='queue')return renderQueue('等待玩家挑戰');if(status==='cards')renderCards();else if(status==='quiz')renderQuiz();else if(status==='wait')renderWait();else if(status==='action')renderAction();else if(status==='resolve')renderResolve();else if(status==='finished')renderEnd();bind()}
  function bind(){app.querySelector('[data-pk-quit]')?.addEventListener('click',()=>stop(true));app.querySelectorAll('[data-pk-card]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.pkCard);if(used.includes(i))return;const at=selected.indexOf(i);if(at>=0)selected.splice(at,1);else if(selected.length<3)selected.push(i);render()}));app.querySelector('[data-pk-confirm]')?.addEventListener('click',()=>beginQuiz(false));app.querySelectorAll('[data-pk-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.pkAnswer,false)));app.querySelector('[data-pk-next]')?.addEventListener('click',next)}
  return {start,stop};
}
